"use client";

import { useState } from "react";
import { CopyButton } from "@/components/copy-button";
import { PageHeader } from "@/components/page-header";
import { TeacherOnly } from "@/components/teacher-only";
import { brand } from "@/config/brand";
import { parentNames, teacherName } from "@/config/family";
import { lessons, type Lesson } from "@/config/lessons";
import { formatDate } from "@/lib/app-state";

// MVP: copy-ready email only.
// FUTURE: automate sending via Gmail API, Resend, SendGrid, or EmailJS —
// build the same `buildEmail` text and POST it from a server action.

function buildEmail(lesson: Lesson): string {
  const videos = lesson.videoLinks.map((v) => `  • ${v.label}: ${v.url}`).join("\n");
  return `Subject: 🌺 Class Prep — ${lesson.title} (${formatDate(lesson.date)})

Hi ${parentNames[0]},

Here's everything the family needs for our next Wonder Journey class!

📚 LESSON
${lesson.emoji} Lesson ${lesson.order}: ${lesson.title}
${lesson.subtitle}

🗓️ WHEN
${formatDate(lesson.date)} at ${lesson.time}

🧺 MATERIALS NEEDED
${lesson.materials.map((m) => `  • ${m}`).join("\n")}

🎨 PRESENTATION
${lesson.canvaLink}

🎬 VIDEOS
${videos}

🏆 FAMILY CHALLENGE
${lesson.familyChallenge}

📝 NOTES
${lesson.notes}

Salamat, and see you in class!

Warmly,
${teacherName}
${brand.productName} — ${brand.worldName}
"${brand.tagline}"`;
}

export default function PrepEmailPage() {
  return (
    <TeacherOnly>
      <PrepEmailContent />
    </TeacherOnly>
  );
}

function PrepEmailContent() {
  const sorted = lessons.slice().sort((a, b) => a.order - b.order);
  const [lessonId, setLessonId] = useState(sorted[0]?.id ?? "");
  const lesson = sorted.find((l) => l.id === lessonId) ?? sorted[0];
  const email = lesson ? buildEmail(lesson) : "";

  return (
    <div className="mx-auto max-w-3xl space-y-6">
      <PageHeader
        emoji="✉️"
        title="Class Prep Email"
        subtitle={`A copy-ready email for ${parentNames.join(" & ")} before each class.`}
      />

      <div className="wj-card p-6">
        <label className="text-sm font-bold text-ink-soft">Choose the upcoming class:</label>
        <select className="wj-input mt-2" value={lessonId} onChange={(e) => setLessonId(e.target.value)}>
          {sorted.map((l) => (
            <option key={l.id} value={l.id}>
              Lesson {l.order}: {l.title} — {formatDate(l.date)}
            </option>
          ))}
        </select>
      </div>

      <div className="wj-card p-6">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <h2 className="font-display text-lg font-extrabold">Preview</h2>
          <CopyButton text={email} label="Copy email 📋" />
        </div>
        <pre className="mt-4 max-h-[32rem] overflow-auto whitespace-pre-wrap rounded-2xl bg-sand p-5 font-body text-sm leading-relaxed">
          {email}
        </pre>
      </div>

      <p className="rounded-2xl bg-ocean/5 p-4 text-xs text-ink-soft">
        💡 For now, paste this into Gmail. Automation with Gmail / Resend / SendGrid / EmailJS is
        planned — the email text is already generated by one function, so hooking up a sender
        later is a small step.
      </p>
    </div>
  );
}
