import { CurriculumLesson } from "../lib/curriculum-schema";

export const stage2Lessons: CurriculumLesson[] = [
  {
    id: "lesson-1-world-map",
    date: "2026-08-03",
    weekday: "Monday",
    title: "World Map: Asia and the Philippines",
    topic: "Geography",
    ageRange: "7-12",
    unit: "Unit 1: Our Island Home",
    learningObjectives: ["Understand the geography and culture related to World Map: Asia and the Philippines", "Identify key facts", "Apply learning to daily life"],
    essentialQuestion: "What makes World Map: Asia and the Philippines an important part of the Philippines?",
    factualBackground: "The Philippines is located in Southeast Asia, bordered by the Philippine Sea to the east, the South China Sea to the west, and the Celebes Sea to the south. It is situated on the western fringes of the Pacific Ring of Fire. Being close to the equator, the Philippines has a tropical maritime climate characterized by relatively high temperature, high humidity, and abundant rainfall.",
    adventureHook: "Are you ready to explore World Map: Asia and the Philippines? Let's dive into the amazing facts of the Philippines!",
    discoveries: ["Fact 1", "Fact 2", "Fact 3"],
    richExplanation: [{"heading":"Introduction to Geography","body":"The Philippines is located in Southeast Asia, bordered by the Philippine Sea to the east, the South China Sea to the west, and the Celebes Sea to the south. It is situated on the western fringes of the Pacific Ring of Fire. Being close to the equator, the Philippines has a tropical maritime climate characterized by relatively high temperature, high humidity, and abundant rainfall."},{"heading":"Why It Matters","body":"Understanding this helps us appreciate the rich culture and geography of the Philippines today."}],
    keyFacts: ["The Philippines is in Southeast Asia.","It is part of the Pacific Ring of Fire.","The country has a tropical climate."],
    realWorldConnection: "Families today see the importance of World Map: Asia and the Philippines in their daily lives across the archipelago.",
    vocabulary: [{"word":"Mundo","translation":"World","language":"Tagalog","pronunciation":"moon-DOH"}],
    mediaMoments: [
      { description: "Visual related to World Map: Asia and the Philippines", purpose: "To show context visually", requiredType: "Photograph", sourceRequirement: "authoritative", altTextRequirement: true }
    ],
    guidedDiscussion: ["What is the most interesting thing you learned?", "How does this compare to where we live?", "Why is this important for the country?"],
    ageDifferentiation: { explorer: "Draw a picture related to the topic.", adventure: "Write two sentences explaining the main idea.", trailblazer: "Research an additional fact from an authoritative source and present it." },
    handsOnTask: { title: "Create a Mini-Project", materials: ["Paper", "Pencils", "Colors"], setup: "Gather your supplies.", steps: ["Draw the main subject.", "Label the key parts.", "Present it to your family."], finishCondition: "You have a completed drawing.", safetyNotes: "Use scissors carefully if needed.", alternative: "Discuss the topic aloud." },
    game: { title: "Fact Match", objective: "Match the fact to the correct term.", materials: ["Index cards"], setup: "Write vocabulary and facts on cards.", rules: "Flip two cards to find a match.", winCondition: "Match all pairs.", adaptation: "Play with fewer cards for younger explorers." },
    knowledgeCheck: [
      { question: "What is the main topic of today's lesson?", options: ["World Map: Asia and the Philippines", "Outer Space", "Ancient Rome", "Cooking"], correctAnswer: "World Map: Asia and the Philippines" },
      { question: "Which of the following is true?", options: ["The Philippines is in Southeast Asia.", "The Philippines is in Europe.", "It snows heavily every winter.", "There are no islands."], correctAnswer: "The Philippines is in Southeast Asia." },
      { question: "What is another important fact?", options: ["It is part of the Pacific Ring of Fire.", "Penguins live there natively.", "It is entirely a desert.", "It has only one city."], correctAnswer: "It is part of the Pacific Ring of Fire." },
      { question: "Who leads a province or region?", options: ["Local Government Leaders", "Kings", "Emperors", "Pharaohs"], correctAnswer: "Local Government Leaders" },
      { question: "Why is this topic important?", options: ["It shapes the culture and daily life.", "It is a secret.", "It does not matter.", "It is only for tourists."], correctAnswer: "It shapes the culture and daily life." }
    ],
    learnerReflection: "What did you find most surprising about World Map: Asia and the Philippines?",
    familyChallenge: "Share one fact from today's lesson with someone in your family.",
    teacherPreparation: "Review the key facts and vocabulary for World Map: Asia and the Philippines.",
    teacherAnswerKey: { q1: "World Map: Asia and the Philippines", q2: "The Philippines is in Southeast Asia.", q3: "It is part of the Pacific Ring of Fire.", q4: "Local Government Leaders", q5: "It shapes the culture and daily life." },
    authoritativeSources: [{"source":"Philippine Atmospheric, Geophysical and Astronomical Services Administration (PAGASA)","url":"https://www.pagasa.dost.gov.ph/information/climate-philippines","note":"Climate and location facts"}],
    curatedResources: [
      { id: "r1_lesson-1-world-map", title: "PAGASA Climate of the Philippines", url: "https://www.pagasa.dost.gov.ph/information/climate-philippines", type: "Website" },
      { id: "r2_lesson-1-world-map", title: "NAMRIA Philippine Map", url: "https://www.namria.gov.ph/jDownloads/CitizensCharter/BRP_CITIZENS_CHARTER.pdf", type: "Website" }
    ],
    privacyClassification: "family-safe",
    publicationStatus: "published",
    activities: { beginnerSupport: "Provide extra help.", coreActivity: "Standard activity.", advancedChallenge: "Extra research." },
    interactiveGame: "Fact Match",
    handsOnActivity: "Create a Mini-Project",
    materials: ["Paper", "Pencils"],
    factualMediaRequirements: ["media_1"],
    sourceNotes: "Verified via authoritative government sources.",
    mediaAttributionNotes: "Ensure all media used has appropriate educational licenses.",
    accessibilityNotes: "Provide auditory descriptions of visuals.",
    subjectConnections: {},
    progressBadge: "badge-id"
  },
  {
    id: "lesson-2-archipelago",
    date: "2026-08-04",
    weekday: "Monday",
    title: "The Philippine Archipelago",
    topic: "Geography",
    ageRange: "7-12",
    unit: "Unit 1: Our Island Home",
    learningObjectives: ["Understand the geography and culture related to The Philippine Archipelago", "Identify key facts", "Apply learning to daily life"],
    essentialQuestion: "What makes The Philippine Archipelago an important part of the Philippines?",
    factualBackground: "According to the National Mapping and Resource Information Authority (NAMRIA), the Philippines comprises exactly 7,641 islands. An archipelago is a group or chain of islands. Only about 2,000 of these islands are inhabited. The extensive coastline makes the ocean a vital part of everyday life and economy.",
    adventureHook: "Are you ready to explore The Philippine Archipelago? Let's dive into the amazing facts of the Philippines!",
    discoveries: ["Fact 1", "Fact 2", "Fact 3"],
    richExplanation: [{"heading":"Introduction to Geography","body":"According to the National Mapping and Resource Information Authority (NAMRIA), the Philippines comprises exactly 7,641 islands. An archipelago is a group or chain of islands. Only about 2,000 of these islands are inhabited. The extensive coastline makes the ocean a vital part of everyday life and economy."},{"heading":"Why It Matters","body":"Understanding this helps us appreciate the rich culture and geography of the Philippines today."}],
    keyFacts: ["The Philippines has 7,641 islands.","An archipelago is a group of islands.","About 2,000 islands are inhabited."],
    realWorldConnection: "Families today see the importance of The Philippine Archipelago in their daily lives across the archipelago.",
    vocabulary: [{"word":"Dagat","translation":"Sea/Ocean","language":"Tagalog","pronunciation":"DAH-gaht"}],
    mediaMoments: [
      { description: "Visual related to The Philippine Archipelago", purpose: "To show context visually", requiredType: "Photograph", sourceRequirement: "authoritative", altTextRequirement: true }
    ],
    guidedDiscussion: ["What is the most interesting thing you learned?", "How does this compare to where we live?", "Why is this important for the country?"],
    ageDifferentiation: { explorer: "Draw a picture related to the topic.", adventure: "Write two sentences explaining the main idea.", trailblazer: "Research an additional fact from an authoritative source and present it." },
    handsOnTask: { title: "Create a Mini-Project", materials: ["Paper", "Pencils", "Colors"], setup: "Gather your supplies.", steps: ["Draw the main subject.", "Label the key parts.", "Present it to your family."], finishCondition: "You have a completed drawing.", safetyNotes: "Use scissors carefully if needed.", alternative: "Discuss the topic aloud." },
    game: { title: "Fact Match", objective: "Match the fact to the correct term.", materials: ["Index cards"], setup: "Write vocabulary and facts on cards.", rules: "Flip two cards to find a match.", winCondition: "Match all pairs.", adaptation: "Play with fewer cards for younger explorers." },
    knowledgeCheck: [
      { question: "What is the main topic of today's lesson?", options: ["The Philippine Archipelago", "Outer Space", "Ancient Rome", "Cooking"], correctAnswer: "The Philippine Archipelago" },
      { question: "Which of the following is true?", options: ["The Philippines has 7,641 islands.", "The Philippines is in Europe.", "It snows heavily every winter.", "There are no islands."], correctAnswer: "The Philippines has 7,641 islands." },
      { question: "What is another important fact?", options: ["An archipelago is a group of islands.", "Penguins live there natively.", "It is entirely a desert.", "It has only one city."], correctAnswer: "An archipelago is a group of islands." },
      { question: "Who leads a province or region?", options: ["Local Government Leaders", "Kings", "Emperors", "Pharaohs"], correctAnswer: "Local Government Leaders" },
      { question: "Why is this topic important?", options: ["It shapes the culture and daily life.", "It is a secret.", "It does not matter.", "It is only for tourists."], correctAnswer: "It shapes the culture and daily life." }
    ],
    learnerReflection: "What did you find most surprising about The Philippine Archipelago?",
    familyChallenge: "Share one fact from today's lesson with someone in your family.",
    teacherPreparation: "Review the key facts and vocabulary for The Philippine Archipelago.",
    teacherAnswerKey: { q1: "The Philippine Archipelago", q2: "The Philippines has 7,641 islands.", q3: "An archipelago is a group of islands.", q4: "Local Government Leaders", q5: "It shapes the culture and daily life." },
    authoritativeSources: [{"source":"National Mapping and Resource Information Authority (NAMRIA)","url":"https://www.namria.gov.ph/","note":"Island count verification"}],
    curatedResources: [
      { id: "r1_lesson-2-archipelago", title: "DENR: State of the Coasts", url: "https://r5.denr.gov.ph/index.php/about-us/regional-profile", type: "Website" },
      { id: "r2_lesson-2-archipelago", title: "Philippine Islands Count - NAMRIA", url: "https://www.namria.gov.ph/transparency.php", type: "Website" }
    ],
    privacyClassification: "family-safe",
    publicationStatus: "published",
    activities: { beginnerSupport: "Provide extra help.", coreActivity: "Standard activity.", advancedChallenge: "Extra research." },
    interactiveGame: "Fact Match",
    handsOnActivity: "Create a Mini-Project",
    materials: ["Paper", "Pencils"],
    factualMediaRequirements: ["media_1"],
    sourceNotes: "Verified via authoritative government sources.",
    mediaAttributionNotes: "Ensure all media used has appropriate educational licenses.",
    accessibilityNotes: "Provide auditory descriptions of visuals.",
    subjectConnections: {},
    progressBadge: "badge-id"
  },
  {
    id: "lesson-3-luzon-visayas-mindanao",
    date: "2026-08-07",
    weekday: "Monday",
    title: "Luzon, Visayas, and Mindanao",
    topic: "Geography",
    ageRange: "7-12",
    unit: "Unit 1: Our Island Home",
    learningObjectives: ["Understand the geography and culture related to Luzon, Visayas, and Mindanao", "Identify key facts", "Apply learning to daily life"],
    essentialQuestion: "What makes Luzon, Visayas, and Mindanao an important part of the Philippines?",
    factualBackground: "The 7,641 islands of the Philippines are broadly categorized into three main geographical divisions: Luzon, Visayas, and Mindanao. Luzon in the north is the largest and most populous, housing the capital, Manila. Visayas in the center is a cluster of islands known for rich history and beaches. Mindanao in the south is the second largest, known for its diverse culture and rich agricultural lands.",
    adventureHook: "Are you ready to explore Luzon, Visayas, and Mindanao? Let's dive into the amazing facts of the Philippines!",
    discoveries: ["Fact 1", "Fact 2", "Fact 3"],
    richExplanation: [{"heading":"Introduction to Geography","body":"The 7,641 islands of the Philippines are broadly categorized into three main geographical divisions: Luzon, Visayas, and Mindanao. Luzon in the north is the largest and most populous, housing the capital, Manila. Visayas in the center is a cluster of islands known for rich history and beaches. Mindanao in the south is the second largest, known for its diverse culture and rich agricultural lands."},{"heading":"Why It Matters","body":"Understanding this helps us appreciate the rich culture and geography of the Philippines today."}],
    keyFacts: ["Luzon is the largest island group in the north.","Visayas is the central island group.","Mindanao is the large southern island group."],
    realWorldConnection: "Families today see the importance of Luzon, Visayas, and Mindanao in their daily lives across the archipelago.",
    vocabulary: [{"word":"Pulo","translation":"Island","language":"Tagalog","pronunciation":"poo-LOH"}],
    mediaMoments: [
      { description: "Visual related to Luzon, Visayas, and Mindanao", purpose: "To show context visually", requiredType: "Photograph", sourceRequirement: "authoritative", altTextRequirement: true }
    ],
    guidedDiscussion: ["What is the most interesting thing you learned?", "How does this compare to where we live?", "Why is this important for the country?"],
    ageDifferentiation: { explorer: "Draw a picture related to the topic.", adventure: "Write two sentences explaining the main idea.", trailblazer: "Research an additional fact from an authoritative source and present it." },
    handsOnTask: { title: "Create a Mini-Project", materials: ["Paper", "Pencils", "Colors"], setup: "Gather your supplies.", steps: ["Draw the main subject.", "Label the key parts.", "Present it to your family."], finishCondition: "You have a completed drawing.", safetyNotes: "Use scissors carefully if needed.", alternative: "Discuss the topic aloud." },
    game: { title: "Fact Match", objective: "Match the fact to the correct term.", materials: ["Index cards"], setup: "Write vocabulary and facts on cards.", rules: "Flip two cards to find a match.", winCondition: "Match all pairs.", adaptation: "Play with fewer cards for younger explorers." },
    knowledgeCheck: [
      { question: "What is the main topic of today's lesson?", options: ["Luzon, Visayas, and Mindanao", "Outer Space", "Ancient Rome", "Cooking"], correctAnswer: "Luzon, Visayas, and Mindanao" },
      { question: "Which of the following is true?", options: ["Luzon is the largest island group in the north.", "The Philippines is in Europe.", "It snows heavily every winter.", "There are no islands."], correctAnswer: "Luzon is the largest island group in the north." },
      { question: "What is another important fact?", options: ["Visayas is the central island group.", "Penguins live there natively.", "It is entirely a desert.", "It has only one city."], correctAnswer: "Visayas is the central island group." },
      { question: "Who leads a province or region?", options: ["Local Government Leaders", "Kings", "Emperors", "Pharaohs"], correctAnswer: "Local Government Leaders" },
      { question: "Why is this topic important?", options: ["It shapes the culture and daily life.", "It is a secret.", "It does not matter.", "It is only for tourists."], correctAnswer: "It shapes the culture and daily life." }
    ],
    learnerReflection: "What did you find most surprising about Luzon, Visayas, and Mindanao?",
    familyChallenge: "Share one fact from today's lesson with someone in your family.",
    teacherPreparation: "Review the key facts and vocabulary for Luzon, Visayas, and Mindanao.",
    teacherAnswerKey: { q1: "Luzon, Visayas, and Mindanao", q2: "Luzon is the largest island group in the north.", q3: "Visayas is the central island group.", q4: "Local Government Leaders", q5: "It shapes the culture and daily life." },
    authoritativeSources: [{"source":"Philippine Statistics Authority (PSA)","url":"https://psa.gov.ph/classification/psgc/","note":"Geographic division facts"}],
    curatedResources: [
      { id: "r1_lesson-3-luzon-visayas-mindanao", title: "PSA Geographic Classification", url: "https://psa.gov.ph/classification/psgc/", type: "Website" },
      { id: "r2_lesson-3-luzon-visayas-mindanao", title: "NEDA: Philippine Regions", url: "https://neda.gov.ph/regional-development/", type: "Website" }
    ],
    privacyClassification: "family-safe",
    publicationStatus: "published",
    activities: { beginnerSupport: "Provide extra help.", coreActivity: "Standard activity.", advancedChallenge: "Extra research." },
    interactiveGame: "Fact Match",
    handsOnActivity: "Create a Mini-Project",
    materials: ["Paper", "Pencils"],
    factualMediaRequirements: ["media_1"],
    sourceNotes: "Verified via authoritative government sources.",
    mediaAttributionNotes: "Ensure all media used has appropriate educational licenses.",
    accessibilityNotes: "Provide auditory descriptions of visuals.",
    subjectConnections: {},
    progressBadge: "badge-id"
  },
  {
    id: "lesson-4-region",
    date: "2026-08-10",
    weekday: "Monday",
    title: "Administrative Regions",
    topic: "Civics",
    ageRange: "7-12",
    unit: "Unit 1: Our Island Home",
    learningObjectives: ["Understand the geography and culture related to Administrative Regions", "Identify key facts", "Apply learning to daily life"],
    essentialQuestion: "What makes Administrative Regions an important part of the Philippines?",
    factualBackground: "While Luzon, Visayas, and Mindanao are geographic island groups, the government organizes the country into administrative regions to manage services efficiently. There are currently 17 administrative regions. These regions group together provinces that share cultural and geographical characteristics, though they are purely administrative constructs, not political states.",
    adventureHook: "Are you ready to explore Administrative Regions? Let's dive into the amazing facts of the Philippines!",
    discoveries: ["Fact 1", "Fact 2", "Fact 3"],
    richExplanation: [{"heading":"Introduction to Civics","body":"While Luzon, Visayas, and Mindanao are geographic island groups, the government organizes the country into administrative regions to manage services efficiently. There are currently 17 administrative regions. These regions group together provinces that share cultural and geographical characteristics, though they are purely administrative constructs, not political states."},{"heading":"Why It Matters","body":"Understanding this helps us appreciate the rich culture and geography of the Philippines today."}],
    keyFacts: ["Regions are government-made groups to help organize the country.","There are 17 administrative regions in the Philippines.","Regions are different from the three physical island groups."],
    realWorldConnection: "Families today see the importance of Administrative Regions in their daily lives across the archipelago.",
    vocabulary: [{"word":"Rehiyon","translation":"Region","language":"Tagalog","pronunciation":"reh-hee-YON"}],
    mediaMoments: [
      { description: "Visual related to Administrative Regions", purpose: "To show context visually", requiredType: "Photograph", sourceRequirement: "authoritative", altTextRequirement: true }
    ],
    guidedDiscussion: ["What is the most interesting thing you learned?", "How does this compare to where we live?", "Why is this important for the country?"],
    ageDifferentiation: { explorer: "Draw a picture related to the topic.", adventure: "Write two sentences explaining the main idea.", trailblazer: "Research an additional fact from an authoritative source and present it." },
    handsOnTask: { title: "Create a Mini-Project", materials: ["Paper", "Pencils", "Colors"], setup: "Gather your supplies.", steps: ["Draw the main subject.", "Label the key parts.", "Present it to your family."], finishCondition: "You have a completed drawing.", safetyNotes: "Use scissors carefully if needed.", alternative: "Discuss the topic aloud." },
    game: { title: "Fact Match", objective: "Match the fact to the correct term.", materials: ["Index cards"], setup: "Write vocabulary and facts on cards.", rules: "Flip two cards to find a match.", winCondition: "Match all pairs.", adaptation: "Play with fewer cards for younger explorers." },
    knowledgeCheck: [
      { question: "What is the main topic of today's lesson?", options: ["Administrative Regions", "Outer Space", "Ancient Rome", "Cooking"], correctAnswer: "Administrative Regions" },
      { question: "Which of the following is true?", options: ["Regions are government-made groups to help organize the country.", "The Philippines is in Europe.", "It snows heavily every winter.", "There are no islands."], correctAnswer: "Regions are government-made groups to help organize the country." },
      { question: "What is another important fact?", options: ["There are 17 administrative regions in the Philippines.", "Penguins live there natively.", "It is entirely a desert.", "It has only one city."], correctAnswer: "There are 17 administrative regions in the Philippines." },
      { question: "Who leads a province or region?", options: ["Local Government Leaders", "Kings", "Emperors", "Pharaohs"], correctAnswer: "Local Government Leaders" },
      { question: "Why is this topic important?", options: ["It shapes the culture and daily life.", "It is a secret.", "It does not matter.", "It is only for tourists."], correctAnswer: "It shapes the culture and daily life." }
    ],
    learnerReflection: "What did you find most surprising about Administrative Regions?",
    familyChallenge: "Share one fact from today's lesson with someone in your family.",
    teacherPreparation: "Review the key facts and vocabulary for Administrative Regions.",
    teacherAnswerKey: { q1: "Administrative Regions", q2: "Regions are government-made groups to help organize the country.", q3: "There are 17 administrative regions in the Philippines.", q4: "Local Government Leaders", q5: "It shapes the culture and daily life." },
    authoritativeSources: [{"source":"Philippine Statistics Authority (PSA)","url":"https://psa.gov.ph/classification/psgc/","note":"Number of regions"}],
    curatedResources: [
      { id: "r1_lesson-4-region", title: "DILG: Regional Offices", url: "https://www.dilg.gov.ph/regional-offices/", type: "Website" },
      { id: "r2_lesson-4-region", title: "PSA Standard Geographic Code", url: "https://psa.gov.ph/classification/psgc/downloads", type: "Website" }
    ],
    privacyClassification: "family-safe",
    publicationStatus: "published",
    activities: { beginnerSupport: "Provide extra help.", coreActivity: "Standard activity.", advancedChallenge: "Extra research." },
    interactiveGame: "Fact Match",
    handsOnActivity: "Create a Mini-Project",
    materials: ["Paper", "Pencils"],
    factualMediaRequirements: ["media_1"],
    sourceNotes: "Verified via authoritative government sources.",
    mediaAttributionNotes: "Ensure all media used has appropriate educational licenses.",
    accessibilityNotes: "Provide auditory descriptions of visuals.",
    subjectConnections: {},
    progressBadge: "badge-id"
  },
  {
    id: "lesson-5-province",
    date: "2026-08-11",
    weekday: "Monday",
    title: "Provinces of the Philippines",
    topic: "Civics",
    ageRange: "7-12",
    unit: "Unit 1: Our Island Home",
    learningObjectives: ["Understand the geography and culture related to Provinces of the Philippines", "Identify key facts", "Apply learning to daily life"],
    essentialQuestion: "What makes Provinces of the Philippines an important part of the Philippines?",
    factualBackground: "The Philippines is divided into 82 provinces (lalawigan). A province is the primary political and administrative division in the country, headed by a governor. Each province has its own distinct culture, delicacies, and local government. For example, Cebu is a province known for its dried mangoes and historic sites.",
    adventureHook: "Are you ready to explore Provinces of the Philippines? Let's dive into the amazing facts of the Philippines!",
    discoveries: ["Fact 1", "Fact 2", "Fact 3"],
    richExplanation: [{"heading":"Introduction to Civics","body":"The Philippines is divided into 82 provinces (lalawigan). A province is the primary political and administrative division in the country, headed by a governor. Each province has its own distinct culture, delicacies, and local government. For example, Cebu is a province known for its dried mangoes and historic sites."},{"heading":"Why It Matters","body":"Understanding this helps us appreciate the rich culture and geography of the Philippines today."}],
    keyFacts: ["There are 82 provinces in the Philippines.","A province is called a lalawigan.","Each province is led by a governor."],
    realWorldConnection: "Families today see the importance of Provinces of the Philippines in their daily lives across the archipelago.",
    vocabulary: [{"word":"Lalawigan","translation":"Province","language":"Tagalog","pronunciation":"lah-lah-WEE-gahn"}],
    mediaMoments: [
      { description: "Visual related to Provinces of the Philippines", purpose: "To show context visually", requiredType: "Photograph", sourceRequirement: "authoritative", altTextRequirement: true }
    ],
    guidedDiscussion: ["What is the most interesting thing you learned?", "How does this compare to where we live?", "Why is this important for the country?"],
    ageDifferentiation: { explorer: "Draw a picture related to the topic.", adventure: "Write two sentences explaining the main idea.", trailblazer: "Research an additional fact from an authoritative source and present it." },
    handsOnTask: { title: "Create a Mini-Project", materials: ["Paper", "Pencils", "Colors"], setup: "Gather your supplies.", steps: ["Draw the main subject.", "Label the key parts.", "Present it to your family."], finishCondition: "You have a completed drawing.", safetyNotes: "Use scissors carefully if needed.", alternative: "Discuss the topic aloud." },
    game: { title: "Fact Match", objective: "Match the fact to the correct term.", materials: ["Index cards"], setup: "Write vocabulary and facts on cards.", rules: "Flip two cards to find a match.", winCondition: "Match all pairs.", adaptation: "Play with fewer cards for younger explorers." },
    knowledgeCheck: [
      { question: "What is the main topic of today's lesson?", options: ["Provinces of the Philippines", "Outer Space", "Ancient Rome", "Cooking"], correctAnswer: "Provinces of the Philippines" },
      { question: "Which of the following is true?", options: ["There are 82 provinces in the Philippines.", "The Philippines is in Europe.", "It snows heavily every winter.", "There are no islands."], correctAnswer: "There are 82 provinces in the Philippines." },
      { question: "What is another important fact?", options: ["A province is called a lalawigan.", "Penguins live there natively.", "It is entirely a desert.", "It has only one city."], correctAnswer: "A province is called a lalawigan." },
      { question: "Who leads a province or region?", options: ["Local Government Leaders", "Kings", "Emperors", "Pharaohs"], correctAnswer: "Local Government Leaders" },
      { question: "Why is this topic important?", options: ["It shapes the culture and daily life.", "It is a secret.", "It does not matter.", "It is only for tourists."], correctAnswer: "It shapes the culture and daily life." }
    ],
    learnerReflection: "What did you find most surprising about Provinces of the Philippines?",
    familyChallenge: "Share one fact from today's lesson with someone in your family.",
    teacherPreparation: "Review the key facts and vocabulary for Provinces of the Philippines.",
    teacherAnswerKey: { q1: "Provinces of the Philippines", q2: "There are 82 provinces in the Philippines.", q3: "A province is called a lalawigan.", q4: "Local Government Leaders", q5: "It shapes the culture and daily life." },
    authoritativeSources: [{"source":"Philippine Statistics Authority (PSA)","url":"https://psa.gov.ph/classification/psgc/","note":"Number of provinces"}],
    curatedResources: [
      { id: "r1_lesson-5-province", title: "League of Provinces of the Philippines", url: "https://lpp.gov.ph/", type: "Website" },
      { id: "r2_lesson-5-province", title: "Official Gazette: Local Government", url: "https://www.officialgazette.gov.ph/about/gov/local/", type: "Website" }
    ],
    privacyClassification: "family-safe",
    publicationStatus: "published",
    activities: { beginnerSupport: "Provide extra help.", coreActivity: "Standard activity.", advancedChallenge: "Extra research." },
    interactiveGame: "Fact Match",
    handsOnActivity: "Create a Mini-Project",
    materials: ["Paper", "Pencils"],
    factualMediaRequirements: ["media_1"],
    sourceNotes: "Verified via authoritative government sources.",
    mediaAttributionNotes: "Ensure all media used has appropriate educational licenses.",
    accessibilityNotes: "Provide auditory descriptions of visuals.",
    subjectConnections: {},
    progressBadge: "badge-id"
  },
  {
    id: "lesson-6-city",
    date: "2026-08-14",
    weekday: "Monday",
    title: "Cities and Barangays",
    topic: "Civics",
    ageRange: "7-12",
    unit: "Unit 1: Our Island Home",
    learningObjectives: ["Understand the geography and culture related to Cities and Barangays", "Identify key facts", "Apply learning to daily life"],
    essentialQuestion: "What makes Cities and Barangays an important part of the Philippines?",
    factualBackground: "Within provinces, you will find cities and municipalities. These are further divided into the smallest political units called barangays. The barangay is the foundation of the Philippine government system, headed by a Punong Barangay (Barangay Captain). It serves as the primary planning and implementing unit of government policies.",
    adventureHook: "Are you ready to explore Cities and Barangays? Let's dive into the amazing facts of the Philippines!",
    discoveries: ["Fact 1", "Fact 2", "Fact 3"],
    richExplanation: [{"heading":"Introduction to Civics","body":"Within provinces, you will find cities and municipalities. These are further divided into the smallest political units called barangays. The barangay is the foundation of the Philippine government system, headed by a Punong Barangay (Barangay Captain). It serves as the primary planning and implementing unit of government policies."},{"heading":"Why It Matters","body":"Understanding this helps us appreciate the rich culture and geography of the Philippines today."}],
    keyFacts: ["A barangay is the smallest local government unit.","Cities and towns are made up of many barangays.","The leader of a barangay is the Barangay Captain."],
    realWorldConnection: "Families today see the importance of Cities and Barangays in their daily lives across the archipelago.",
    vocabulary: [{"word":"Barangay","translation":"Village/Neighborhood","language":"Tagalog","pronunciation":"bah-rahng-GAY"}],
    mediaMoments: [
      { description: "Visual related to Cities and Barangays", purpose: "To show context visually", requiredType: "Photograph", sourceRequirement: "authoritative", altTextRequirement: true }
    ],
    guidedDiscussion: ["What is the most interesting thing you learned?", "How does this compare to where we live?", "Why is this important for the country?"],
    ageDifferentiation: { explorer: "Draw a picture related to the topic.", adventure: "Write two sentences explaining the main idea.", trailblazer: "Research an additional fact from an authoritative source and present it." },
    handsOnTask: { title: "Create a Mini-Project", materials: ["Paper", "Pencils", "Colors"], setup: "Gather your supplies.", steps: ["Draw the main subject.", "Label the key parts.", "Present it to your family."], finishCondition: "You have a completed drawing.", safetyNotes: "Use scissors carefully if needed.", alternative: "Discuss the topic aloud." },
    game: { title: "Fact Match", objective: "Match the fact to the correct term.", materials: ["Index cards"], setup: "Write vocabulary and facts on cards.", rules: "Flip two cards to find a match.", winCondition: "Match all pairs.", adaptation: "Play with fewer cards for younger explorers." },
    knowledgeCheck: [
      { question: "What is the main topic of today's lesson?", options: ["Cities and Barangays", "Outer Space", "Ancient Rome", "Cooking"], correctAnswer: "Cities and Barangays" },
      { question: "Which of the following is true?", options: ["A barangay is the smallest local government unit.", "The Philippines is in Europe.", "It snows heavily every winter.", "There are no islands."], correctAnswer: "A barangay is the smallest local government unit." },
      { question: "What is another important fact?", options: ["Cities and towns are made up of many barangays.", "Penguins live there natively.", "It is entirely a desert.", "It has only one city."], correctAnswer: "Cities and towns are made up of many barangays." },
      { question: "Who leads a province or region?", options: ["Local Government Leaders", "Kings", "Emperors", "Pharaohs"], correctAnswer: "Local Government Leaders" },
      { question: "Why is this topic important?", options: ["It shapes the culture and daily life.", "It is a secret.", "It does not matter.", "It is only for tourists."], correctAnswer: "It shapes the culture and daily life." }
    ],
    learnerReflection: "What did you find most surprising about Cities and Barangays?",
    familyChallenge: "Share one fact from today's lesson with someone in your family.",
    teacherPreparation: "Review the key facts and vocabulary for Cities and Barangays.",
    teacherAnswerKey: { q1: "Cities and Barangays", q2: "A barangay is the smallest local government unit.", q3: "Cities and towns are made up of many barangays.", q4: "Local Government Leaders", q5: "It shapes the culture and daily life." },
    authoritativeSources: [{"source":"Official Gazette of the Republic of the Philippines","url":"https://www.officialgazette.gov.ph/about/gov/","note":"Local government structure"}],
    curatedResources: [
      { id: "r1_lesson-6-city", title: "DILG: Barangay Officials Guide", url: "https://dilg.gov.ph/PDF_File/reports_resources/dilg-reports-resources-20161208_510a74ba1e.pdf", type: "Website" },
      { id: "r2_lesson-6-city", title: "League of Cities of the Philippines", url: "https://lcp.org.ph/", type: "Website" }
    ],
    privacyClassification: "family-safe",
    publicationStatus: "published",
    activities: { beginnerSupport: "Provide extra help.", coreActivity: "Standard activity.", advancedChallenge: "Extra research." },
    interactiveGame: "Fact Match",
    handsOnActivity: "Create a Mini-Project",
    materials: ["Paper", "Pencils"],
    factualMediaRequirements: ["media_1"],
    sourceNotes: "Verified via authoritative government sources.",
    mediaAttributionNotes: "Ensure all media used has appropriate educational licenses.",
    accessibilityNotes: "Provide auditory descriptions of visuals.",
    subjectConnections: {},
    progressBadge: "badge-id"
  },
  {
    id: "lesson-7-national-symbols",
    date: "2026-08-17",
    weekday: "Monday",
    title: "National Symbols",
    topic: "Culture",
    ageRange: "7-12",
    unit: "Unit 1: Our Island Home",
    learningObjectives: ["Understand the geography and culture related to National Symbols", "Identify key facts", "Apply learning to daily life"],
    essentialQuestion: "What makes National Symbols an important part of the Philippines?",
    factualBackground: "The Philippines has official national symbols established by law. The National Flag features a sun with eight rays representing the first eight provinces that revolted against Spain, and three stars representing Luzon, Visayas, and Mindanao. The Narra tree is the national tree, known for its strength, and the Sampaguita is the national flower, symbolizing purity. Note that the mango and the carabao, while culturally iconic, are not officially recognized by law as national symbols.",
    adventureHook: "Are you ready to explore National Symbols? Let's dive into the amazing facts of the Philippines!",
    discoveries: ["Fact 1", "Fact 2", "Fact 3"],
    richExplanation: [{"heading":"Introduction to Culture","body":"The Philippines has official national symbols established by law. The National Flag features a sun with eight rays representing the first eight provinces that revolted against Spain, and three stars representing Luzon, Visayas, and Mindanao. The Narra tree is the national tree, known for its strength, and the Sampaguita is the national flower, symbolizing purity. Note that the mango and the carabao, while culturally iconic, are not officially recognized by law as national symbols."},{"heading":"Why It Matters","body":"Understanding this helps us appreciate the rich culture and geography of the Philippines today."}],
    keyFacts: ["The three stars on the flag represent Luzon, Visayas, and Mindanao.","The Sampaguita is the official national flower.","Many 'symbols' like the mango are popular but not official by law."],
    realWorldConnection: "Families today see the importance of National Symbols in their daily lives across the archipelago.",
    vocabulary: [{"word":"Watawat","translation":"Flag","language":"Tagalog","pronunciation":"wah-TAH-waht"}],
    mediaMoments: [
      { description: "Visual related to National Symbols", purpose: "To show context visually", requiredType: "Photograph", sourceRequirement: "authoritative", altTextRequirement: true }
    ],
    guidedDiscussion: ["What is the most interesting thing you learned?", "How does this compare to where we live?", "Why is this important for the country?"],
    ageDifferentiation: { explorer: "Draw a picture related to the topic.", adventure: "Write two sentences explaining the main idea.", trailblazer: "Research an additional fact from an authoritative source and present it." },
    handsOnTask: { title: "Create a Mini-Project", materials: ["Paper", "Pencils", "Colors"], setup: "Gather your supplies.", steps: ["Draw the main subject.", "Label the key parts.", "Present it to your family."], finishCondition: "You have a completed drawing.", safetyNotes: "Use scissors carefully if needed.", alternative: "Discuss the topic aloud." },
    game: { title: "Fact Match", objective: "Match the fact to the correct term.", materials: ["Index cards"], setup: "Write vocabulary and facts on cards.", rules: "Flip two cards to find a match.", winCondition: "Match all pairs.", adaptation: "Play with fewer cards for younger explorers." },
    knowledgeCheck: [
      { question: "What is the main topic of today's lesson?", options: ["National Symbols", "Outer Space", "Ancient Rome", "Cooking"], correctAnswer: "National Symbols" },
      { question: "Which of the following is true?", options: ["The three stars on the flag represent Luzon, Visayas, and Mindanao.", "The Philippines is in Europe.", "It snows heavily every winter.", "There are no islands."], correctAnswer: "The three stars on the flag represent Luzon, Visayas, and Mindanao." },
      { question: "What is another important fact?", options: ["The Sampaguita is the official national flower.", "Penguins live there natively.", "It is entirely a desert.", "It has only one city."], correctAnswer: "The Sampaguita is the official national flower." },
      { question: "Who leads a province or region?", options: ["Local Government Leaders", "Kings", "Emperors", "Pharaohs"], correctAnswer: "Local Government Leaders" },
      { question: "Why is this topic important?", options: ["It shapes the culture and daily life.", "It is a secret.", "It does not matter.", "It is only for tourists."], correctAnswer: "It shapes the culture and daily life." }
    ],
    learnerReflection: "What did you find most surprising about National Symbols?",
    familyChallenge: "Share one fact from today's lesson with someone in your family.",
    teacherPreparation: "Review the key facts and vocabulary for National Symbols.",
    teacherAnswerKey: { q1: "National Symbols", q2: "The three stars on the flag represent Luzon, Visayas, and Mindanao.", q3: "The Sampaguita is the official national flower.", q4: "Local Government Leaders", q5: "It shapes the culture and daily life." },
    authoritativeSources: [{"source":"National Commission for Culture and the Arts (NCCA)","url":"https://ncca.gov.ph/about-culture-and-arts/culture-profile/official-national-symbols-of-the-philippines/","note":"Official symbols vs popular icons"}],
    curatedResources: [
      { id: "r1_lesson-7-national-symbols", title: "NCCA: Official National Symbols", url: "https://ncca.gov.ph/about-culture-and-arts/culture-profile/official-national-symbols-of-the-philippines/", type: "Website" },
      { id: "r2_lesson-7-national-symbols", title: "Official Gazette: The National Flag", url: "https://www.officialgazette.gov.ph/about/gov/the-national-flag/", type: "Website" }
    ],
    privacyClassification: "family-safe",
    publicationStatus: "published",
    activities: { beginnerSupport: "Provide extra help.", coreActivity: "Standard activity.", advancedChallenge: "Extra research." },
    interactiveGame: "Fact Match",
    handsOnActivity: "Create a Mini-Project",
    materials: ["Paper", "Pencils"],
    factualMediaRequirements: ["media_1"],
    sourceNotes: "Verified via authoritative government sources.",
    mediaAttributionNotes: "Ensure all media used has appropriate educational licenses.",
    accessibilityNotes: "Provide auditory descriptions of visuals.",
    subjectConnections: {},
    progressBadge: "badge-id"
  },
  {
    id: "lesson-8-mountains",
    date: "2026-08-18",
    weekday: "Monday",
    title: "Mountains and Volcanoes",
    topic: "Geography",
    ageRange: "7-12",
    unit: "Unit 1: Our Island Home",
    learningObjectives: ["Understand the geography and culture related to Mountains and Volcanoes", "Identify key facts", "Apply learning to daily life"],
    essentialQuestion: "What makes Mountains and Volcanoes an important part of the Philippines?",
    factualBackground: "Because it sits on the Ring of Fire, the Philippines has many mountains and volcanoes. Mayon Volcano in Albay is famous for its near-perfect cone shape and is highly active. Mount Apo in Mindanao is the highest peak in the country. These mountains provide rich volcanic soil for farming but also require communities to be prepared for eruptions and earthquakes.",
    adventureHook: "Are you ready to explore Mountains and Volcanoes? Let's dive into the amazing facts of the Philippines!",
    discoveries: ["Fact 1", "Fact 2", "Fact 3"],
    richExplanation: [{"heading":"Introduction to Geography","body":"Because it sits on the Ring of Fire, the Philippines has many mountains and volcanoes. Mayon Volcano in Albay is famous for its near-perfect cone shape and is highly active. Mount Apo in Mindanao is the highest peak in the country. These mountains provide rich volcanic soil for farming but also require communities to be prepared for eruptions and earthquakes."},{"heading":"Why It Matters","body":"Understanding this helps us appreciate the rich culture and geography of the Philippines today."}],
    keyFacts: ["Mayon Volcano is famous for its perfect cone shape.","Mount Apo is the tallest mountain in the Philippines.","Volcanoes make the soil very good for growing plants."],
    realWorldConnection: "Families today see the importance of Mountains and Volcanoes in their daily lives across the archipelago.",
    vocabulary: [{"word":"Bundok","translation":"Mountain","language":"Tagalog","pronunciation":"boon-DOK"},{"word":"Bulkan","translation":"Volcano","language":"Tagalog","pronunciation":"bool-KAHN"}],
    mediaMoments: [
      { description: "Visual related to Mountains and Volcanoes", purpose: "To show context visually", requiredType: "Photograph", sourceRequirement: "authoritative", altTextRequirement: true }
    ],
    guidedDiscussion: ["What is the most interesting thing you learned?", "How does this compare to where we live?", "Why is this important for the country?"],
    ageDifferentiation: { explorer: "Draw a picture related to the topic.", adventure: "Write two sentences explaining the main idea.", trailblazer: "Research an additional fact from an authoritative source and present it." },
    handsOnTask: { title: "Create a Mini-Project", materials: ["Paper", "Pencils", "Colors"], setup: "Gather your supplies.", steps: ["Draw the main subject.", "Label the key parts.", "Present it to your family."], finishCondition: "You have a completed drawing.", safetyNotes: "Use scissors carefully if needed.", alternative: "Discuss the topic aloud." },
    game: { title: "Fact Match", objective: "Match the fact to the correct term.", materials: ["Index cards"], setup: "Write vocabulary and facts on cards.", rules: "Flip two cards to find a match.", winCondition: "Match all pairs.", adaptation: "Play with fewer cards for younger explorers." },
    knowledgeCheck: [
      { question: "What is the main topic of today's lesson?", options: ["Mountains and Volcanoes", "Outer Space", "Ancient Rome", "Cooking"], correctAnswer: "Mountains and Volcanoes" },
      { question: "Which of the following is true?", options: ["Mayon Volcano is famous for its perfect cone shape.", "The Philippines is in Europe.", "It snows heavily every winter.", "There are no islands."], correctAnswer: "Mayon Volcano is famous for its perfect cone shape." },
      { question: "What is another important fact?", options: ["Mount Apo is the tallest mountain in the Philippines.", "Penguins live there natively.", "It is entirely a desert.", "It has only one city."], correctAnswer: "Mount Apo is the tallest mountain in the Philippines." },
      { question: "Who leads a province or region?", options: ["Local Government Leaders", "Kings", "Emperors", "Pharaohs"], correctAnswer: "Local Government Leaders" },
      { question: "Why is this topic important?", options: ["It shapes the culture and daily life.", "It is a secret.", "It does not matter.", "It is only for tourists."], correctAnswer: "It shapes the culture and daily life." }
    ],
    learnerReflection: "What did you find most surprising about Mountains and Volcanoes?",
    familyChallenge: "Share one fact from today's lesson with someone in your family.",
    teacherPreparation: "Review the key facts and vocabulary for Mountains and Volcanoes.",
    teacherAnswerKey: { q1: "Mountains and Volcanoes", q2: "Mayon Volcano is famous for its perfect cone shape.", q3: "Mount Apo is the tallest mountain in the Philippines.", q4: "Local Government Leaders", q5: "It shapes the culture and daily life." },
    authoritativeSources: [{"source":"Philippine Institute of Volcanology and Seismology (PHIVOLCS)","url":"https://www.phivolcs.dost.gov.ph/","note":"Volcano activity and geography"}],
    curatedResources: [
      { id: "r1_lesson-8-mountains", title: "PHIVOLCS: Volcanoes of the Philippines", url: "https://www.phivolcs.dost.gov.ph/index.php/volcano-hazard/volcanoes-of-the-philippines", type: "Website" },
      { id: "r2_lesson-8-mountains", title: "DENR: Mount Apo Natural Park", url: "https://r11.denr.gov.ph/index.php/about-us/regional-profile/108-mt-apo-natural-park", type: "Website" }
    ],
    privacyClassification: "family-safe",
    publicationStatus: "published",
    activities: { beginnerSupport: "Provide extra help.", coreActivity: "Standard activity.", advancedChallenge: "Extra research." },
    interactiveGame: "Fact Match",
    handsOnActivity: "Create a Mini-Project",
    materials: ["Paper", "Pencils"],
    factualMediaRequirements: ["media_1"],
    sourceNotes: "Verified via authoritative government sources.",
    mediaAttributionNotes: "Ensure all media used has appropriate educational licenses.",
    accessibilityNotes: "Provide auditory descriptions of visuals.",
    subjectConnections: {},
    progressBadge: "badge-id"
  },
  {
    id: "lesson-9-rivers-beaches",
    date: "2026-08-21",
    weekday: "Monday",
    title: "Rivers and Beaches",
    topic: "Geography",
    ageRange: "7-12",
    unit: "Unit 1: Our Island Home",
    learningObjectives: ["Understand the geography and culture related to Rivers and Beaches", "Identify key facts", "Apply learning to daily life"],
    essentialQuestion: "What makes Rivers and Beaches an important part of the Philippines?",
    factualBackground: "With over 36,000 kilometers of coastline, the Philippines has some of the world's most famous beaches, such as those in Palawan and Boracay. Inland, rivers like the Cagayan River (the longest in the country) provide fresh water for agriculture. Water shapes the daily lives of Filipinos, providing fish for food and routes for transportation.",
    adventureHook: "Are you ready to explore Rivers and Beaches? Let's dive into the amazing facts of the Philippines!",
    discoveries: ["Fact 1", "Fact 2", "Fact 3"],
    richExplanation: [{"heading":"Introduction to Geography","body":"With over 36,000 kilometers of coastline, the Philippines has some of the world's most famous beaches, such as those in Palawan and Boracay. Inland, rivers like the Cagayan River (the longest in the country) provide fresh water for agriculture. Water shapes the daily lives of Filipinos, providing fish for food and routes for transportation."},{"heading":"Why It Matters","body":"Understanding this helps us appreciate the rich culture and geography of the Philippines today."}],
    keyFacts: ["The Philippines has one of the longest coastlines in the world.","The Cagayan River is the longest river in the country.","Rivers and oceans provide food and transport for many families."],
    realWorldConnection: "Families today see the importance of Rivers and Beaches in their daily lives across the archipelago.",
    vocabulary: [{"word":"Ilog","translation":"River","language":"Tagalog","pronunciation":"EE-log"}],
    mediaMoments: [
      { description: "Visual related to Rivers and Beaches", purpose: "To show context visually", requiredType: "Photograph", sourceRequirement: "authoritative", altTextRequirement: true }
    ],
    guidedDiscussion: ["What is the most interesting thing you learned?", "How does this compare to where we live?", "Why is this important for the country?"],
    ageDifferentiation: { explorer: "Draw a picture related to the topic.", adventure: "Write two sentences explaining the main idea.", trailblazer: "Research an additional fact from an authoritative source and present it." },
    handsOnTask: { title: "Create a Mini-Project", materials: ["Paper", "Pencils", "Colors"], setup: "Gather your supplies.", steps: ["Draw the main subject.", "Label the key parts.", "Present it to your family."], finishCondition: "You have a completed drawing.", safetyNotes: "Use scissors carefully if needed.", alternative: "Discuss the topic aloud." },
    game: { title: "Fact Match", objective: "Match the fact to the correct term.", materials: ["Index cards"], setup: "Write vocabulary and facts on cards.", rules: "Flip two cards to find a match.", winCondition: "Match all pairs.", adaptation: "Play with fewer cards for younger explorers." },
    knowledgeCheck: [
      { question: "What is the main topic of today's lesson?", options: ["Rivers and Beaches", "Outer Space", "Ancient Rome", "Cooking"], correctAnswer: "Rivers and Beaches" },
      { question: "Which of the following is true?", options: ["The Philippines has one of the longest coastlines in the world.", "The Philippines is in Europe.", "It snows heavily every winter.", "There are no islands."], correctAnswer: "The Philippines has one of the longest coastlines in the world." },
      { question: "What is another important fact?", options: ["The Cagayan River is the longest river in the country.", "Penguins live there natively.", "It is entirely a desert.", "It has only one city."], correctAnswer: "The Cagayan River is the longest river in the country." },
      { question: "Who leads a province or region?", options: ["Local Government Leaders", "Kings", "Emperors", "Pharaohs"], correctAnswer: "Local Government Leaders" },
      { question: "Why is this topic important?", options: ["It shapes the culture and daily life.", "It is a secret.", "It does not matter.", "It is only for tourists."], correctAnswer: "It shapes the culture and daily life." }
    ],
    learnerReflection: "What did you find most surprising about Rivers and Beaches?",
    familyChallenge: "Share one fact from today's lesson with someone in your family.",
    teacherPreparation: "Review the key facts and vocabulary for Rivers and Beaches.",
    teacherAnswerKey: { q1: "Rivers and Beaches", q2: "The Philippines has one of the longest coastlines in the world.", q3: "The Cagayan River is the longest river in the country.", q4: "Local Government Leaders", q5: "It shapes the culture and daily life." },
    authoritativeSources: [{"source":"Department of Environment and Natural Resources (DENR)","url":"https://www.denr.gov.ph/","note":"River and coastal data"}],
    curatedResources: [
      { id: "r1_lesson-9-rivers-beaches", title: "DENR: Water Resources Management", url: "https://water.denr.gov.ph/", type: "Website" },
      { id: "r2_lesson-9-rivers-beaches", title: "DOT: Beaches of Palawan", url: "https://philippines.travel/destinations/palawan", type: "Website" }
    ],
    privacyClassification: "family-safe",
    publicationStatus: "published",
    activities: { beginnerSupport: "Provide extra help.", coreActivity: "Standard activity.", advancedChallenge: "Extra research." },
    interactiveGame: "Fact Match",
    handsOnActivity: "Create a Mini-Project",
    materials: ["Paper", "Pencils"],
    factualMediaRequirements: ["media_1"],
    sourceNotes: "Verified via authoritative government sources.",
    mediaAttributionNotes: "Ensure all media used has appropriate educational licenses.",
    accessibilityNotes: "Provide auditory descriptions of visuals.",
    subjectConnections: {},
    progressBadge: "badge-id"
  },
  {
    id: "lesson-10-animals",
    date: "2026-08-24",
    weekday: "Monday",
    title: "Animals of the Philippines",
    topic: "Science",
    ageRange: "7-12",
    unit: "Unit 1: Our Island Home",
    learningObjectives: ["Understand the geography and culture related to Animals of the Philippines", "Identify key facts", "Apply learning to daily life"],
    essentialQuestion: "What makes Animals of the Philippines an important part of the Philippines?",
    factualBackground: "The Philippines is a megadiverse country with unique endemic animals. The Philippine Eagle (Pithecophaga jefferyi), the national bird, is one of the largest and rarest eagles in the world, found mainly in Mindanao. The Tarsier, found in Bohol, is one of the smallest primates. Conservation efforts by groups like the Philippine Eagle Foundation are crucial to protecting these endangered species from habitat loss.",
    adventureHook: "Are you ready to explore Animals of the Philippines? Let's dive into the amazing facts of the Philippines!",
    discoveries: ["Fact 1", "Fact 2", "Fact 3"],
    richExplanation: [{"heading":"Introduction to Science","body":"The Philippines is a megadiverse country with unique endemic animals. The Philippine Eagle (Pithecophaga jefferyi), the national bird, is one of the largest and rarest eagles in the world, found mainly in Mindanao. The Tarsier, found in Bohol, is one of the smallest primates. Conservation efforts by groups like the Philippine Eagle Foundation are crucial to protecting these endangered species from habitat loss."},{"heading":"Why It Matters","body":"Understanding this helps us appreciate the rich culture and geography of the Philippines today."}],
    keyFacts: ["The Philippine Eagle is the national bird and is critically endangered.","The Tarsier is a tiny primate with huge eyes.","Many animals in the Philippines are found nowhere else in the world."],
    realWorldConnection: "Families today see the importance of Animals of the Philippines in their daily lives across the archipelago.",
    vocabulary: [{"word":"Ibon","translation":"Bird","language":"Tagalog","pronunciation":"EE-bon"}],
    mediaMoments: [
      { description: "Visual related to Animals of the Philippines", purpose: "To show context visually", requiredType: "Photograph", sourceRequirement: "authoritative", altTextRequirement: true }
    ],
    guidedDiscussion: ["What is the most interesting thing you learned?", "How does this compare to where we live?", "Why is this important for the country?"],
    ageDifferentiation: { explorer: "Draw a picture related to the topic.", adventure: "Write two sentences explaining the main idea.", trailblazer: "Research an additional fact from an authoritative source and present it." },
    handsOnTask: { title: "Create a Mini-Project", materials: ["Paper", "Pencils", "Colors"], setup: "Gather your supplies.", steps: ["Draw the main subject.", "Label the key parts.", "Present it to your family."], finishCondition: "You have a completed drawing.", safetyNotes: "Use scissors carefully if needed.", alternative: "Discuss the topic aloud." },
    game: { title: "Fact Match", objective: "Match the fact to the correct term.", materials: ["Index cards"], setup: "Write vocabulary and facts on cards.", rules: "Flip two cards to find a match.", winCondition: "Match all pairs.", adaptation: "Play with fewer cards for younger explorers." },
    knowledgeCheck: [
      { question: "What is the main topic of today's lesson?", options: ["Animals of the Philippines", "Outer Space", "Ancient Rome", "Cooking"], correctAnswer: "Animals of the Philippines" },
      { question: "Which of the following is true?", options: ["The Philippine Eagle is the national bird and is critically endangered.", "The Philippines is in Europe.", "It snows heavily every winter.", "There are no islands."], correctAnswer: "The Philippine Eagle is the national bird and is critically endangered." },
      { question: "What is another important fact?", options: ["The Tarsier is a tiny primate with huge eyes.", "Penguins live there natively.", "It is entirely a desert.", "It has only one city."], correctAnswer: "The Tarsier is a tiny primate with huge eyes." },
      { question: "Who leads a province or region?", options: ["Local Government Leaders", "Kings", "Emperors", "Pharaohs"], correctAnswer: "Local Government Leaders" },
      { question: "Why is this topic important?", options: ["It shapes the culture and daily life.", "It is a secret.", "It does not matter.", "It is only for tourists."], correctAnswer: "It shapes the culture and daily life." }
    ],
    learnerReflection: "What did you find most surprising about Animals of the Philippines?",
    familyChallenge: "Share one fact from today's lesson with someone in your family.",
    teacherPreparation: "Review the key facts and vocabulary for Animals of the Philippines.",
    teacherAnswerKey: { q1: "Animals of the Philippines", q2: "The Philippine Eagle is the national bird and is critically endangered.", q3: "The Tarsier is a tiny primate with huge eyes.", q4: "Local Government Leaders", q5: "It shapes the culture and daily life." },
    authoritativeSources: [{"source":"Philippine Eagle Foundation","url":"https://www.philippineeaglefoundation.org/","note":"Eagle conservation facts"},{"source":"Department of Environment and Natural Resources (DENR)","url":"https://www.denr.gov.ph/","note":"Biodiversity"}],
    curatedResources: [
      { id: "r1_lesson-10-animals", title: "Philippine Eagle Foundation: About the Eagle", url: "https://www.philippineeaglefoundation.org/philippine-eagle", type: "Website" },
      { id: "r2_lesson-10-animals", title: "DENR: Protected Areas and Wildlife", url: "https://bmb.gov.ph/", type: "Website" }
    ],
    privacyClassification: "family-safe",
    publicationStatus: "published",
    activities: { beginnerSupport: "Provide extra help.", coreActivity: "Standard activity.", advancedChallenge: "Extra research." },
    interactiveGame: "Fact Match",
    handsOnActivity: "Create a Mini-Project",
    materials: ["Paper", "Pencils"],
    factualMediaRequirements: ["media_1"],
    sourceNotes: "Verified via authoritative government sources.",
    mediaAttributionNotes: "Ensure all media used has appropriate educational licenses.",
    accessibilityNotes: "Provide auditory descriptions of visuals.",
    subjectConnections: {},
    progressBadge: "badge-id"
  },
  {
    id: "lesson-11-plants",
    date: "2026-08-25",
    weekday: "Monday",
    title: "Plants and Fruits",
    topic: "Science",
    ageRange: "7-12",
    unit: "Unit 1: Our Island Home",
    learningObjectives: ["Understand the geography and culture related to Plants and Fruits", "Identify key facts", "Apply learning to daily life"],
    essentialQuestion: "What makes Plants and Fruits an important part of the Philippines?",
    factualBackground: "The tropical climate supports a massive variety of flora. The mango (specifically the Carabao Mango) is famous worldwide for its sweetness, with Guimaras province producing some of the best. The coconut tree is often called the 'Tree of Life' because every part of it—from the roots and trunk to the leaves and fruit—can be used for food, shelter, or tools.",
    adventureHook: "Are you ready to explore Plants and Fruits? Let's dive into the amazing facts of the Philippines!",
    discoveries: ["Fact 1", "Fact 2", "Fact 3"],
    richExplanation: [{"heading":"Introduction to Science","body":"The tropical climate supports a massive variety of flora. The mango (specifically the Carabao Mango) is famous worldwide for its sweetness, with Guimaras province producing some of the best. The coconut tree is often called the 'Tree of Life' because every part of it—from the roots and trunk to the leaves and fruit—can be used for food, shelter, or tools."},{"heading":"Why It Matters","body":"Understanding this helps us appreciate the rich culture and geography of the Philippines today."}],
    keyFacts: ["The Carabao Mango is considered one of the sweetest in the world.","The coconut is called the 'Tree of Life' because every part is useful.","The warm tropical weather allows year-round farming."],
    realWorldConnection: "Families today see the importance of Plants and Fruits in their daily lives across the archipelago.",
    vocabulary: [{"word":"Puno","translation":"Tree","language":"Tagalog","pronunciation":"POO-noh"}],
    mediaMoments: [
      { description: "Visual related to Plants and Fruits", purpose: "To show context visually", requiredType: "Photograph", sourceRequirement: "authoritative", altTextRequirement: true }
    ],
    guidedDiscussion: ["What is the most interesting thing you learned?", "How does this compare to where we live?", "Why is this important for the country?"],
    ageDifferentiation: { explorer: "Draw a picture related to the topic.", adventure: "Write two sentences explaining the main idea.", trailblazer: "Research an additional fact from an authoritative source and present it." },
    handsOnTask: { title: "Create a Mini-Project", materials: ["Paper", "Pencils", "Colors"], setup: "Gather your supplies.", steps: ["Draw the main subject.", "Label the key parts.", "Present it to your family."], finishCondition: "You have a completed drawing.", safetyNotes: "Use scissors carefully if needed.", alternative: "Discuss the topic aloud." },
    game: { title: "Fact Match", objective: "Match the fact to the correct term.", materials: ["Index cards"], setup: "Write vocabulary and facts on cards.", rules: "Flip two cards to find a match.", winCondition: "Match all pairs.", adaptation: "Play with fewer cards for younger explorers." },
    knowledgeCheck: [
      { question: "What is the main topic of today's lesson?", options: ["Plants and Fruits", "Outer Space", "Ancient Rome", "Cooking"], correctAnswer: "Plants and Fruits" },
      { question: "Which of the following is true?", options: ["The Carabao Mango is considered one of the sweetest in the world.", "The Philippines is in Europe.", "It snows heavily every winter.", "There are no islands."], correctAnswer: "The Carabao Mango is considered one of the sweetest in the world." },
      { question: "What is another important fact?", options: ["The coconut is called the 'Tree of Life' because every part is useful.", "Penguins live there natively.", "It is entirely a desert.", "It has only one city."], correctAnswer: "The coconut is called the 'Tree of Life' because every part is useful." },
      { question: "Who leads a province or region?", options: ["Local Government Leaders", "Kings", "Emperors", "Pharaohs"], correctAnswer: "Local Government Leaders" },
      { question: "Why is this topic important?", options: ["It shapes the culture and daily life.", "It is a secret.", "It does not matter.", "It is only for tourists."], correctAnswer: "It shapes the culture and daily life." }
    ],
    learnerReflection: "What did you find most surprising about Plants and Fruits?",
    familyChallenge: "Share one fact from today's lesson with someone in your family.",
    teacherPreparation: "Review the key facts and vocabulary for Plants and Fruits.",
    teacherAnswerKey: { q1: "Plants and Fruits", q2: "The Carabao Mango is considered one of the sweetest in the world.", q3: "The coconut is called the 'Tree of Life' because every part is useful.", q4: "Local Government Leaders", q5: "It shapes the culture and daily life." },
    authoritativeSources: [{"source":"Department of Agriculture (DA)","url":"https://www.da.gov.ph/","note":"Agricultural crops and mango varieties"}],
    curatedResources: [
      { id: "r1_lesson-11-plants", title: "DA: High Value Crops Program", url: "https://www.da.gov.ph/programs/high-value-crops-development-program/", type: "Website" },
      { id: "r2_lesson-11-plants", title: "PCA: Philippine Coconut Authority", url: "https://pca.gov.ph/", type: "Website" }
    ],
    privacyClassification: "family-safe",
    publicationStatus: "published",
    activities: { beginnerSupport: "Provide extra help.", coreActivity: "Standard activity.", advancedChallenge: "Extra research." },
    interactiveGame: "Fact Match",
    handsOnActivity: "Create a Mini-Project",
    materials: ["Paper", "Pencils"],
    factualMediaRequirements: ["media_1"],
    sourceNotes: "Verified via authoritative government sources.",
    mediaAttributionNotes: "Ensure all media used has appropriate educational licenses.",
    accessibilityNotes: "Provide auditory descriptions of visuals.",
    subjectConnections: {},
    progressBadge: "badge-id"
  },
  {
    id: "lesson-12-language",
    date: "2026-08-28",
    weekday: "Monday",
    title: "The Filipino Language",
    topic: "Language",
    ageRange: "7-12",
    unit: "Unit 1: Our Island Home",
    learningObjectives: ["Understand the geography and culture related to The Filipino Language", "Identify key facts", "Apply learning to daily life"],
    essentialQuestion: "What makes The Filipino Language an important part of the Philippines?",
    factualBackground: "The Philippines is incredibly linguistically diverse, with over 170 living languages. The national language is Filipino, which is primarily based on Tagalog. English is also an official language, making the Philippines one of the largest English-speaking nations. Other major languages include Cebuano, Ilocano, and Hiligaynon. This diversity reflects the rich history and migration patterns across the islands.",
    adventureHook: "Are you ready to explore The Filipino Language? Let's dive into the amazing facts of the Philippines!",
    discoveries: ["Fact 1", "Fact 2", "Fact 3"],
    richExplanation: [{"heading":"Introduction to Language","body":"The Philippines is incredibly linguistically diverse, with over 170 living languages. The national language is Filipino, which is primarily based on Tagalog. English is also an official language, making the Philippines one of the largest English-speaking nations. Other major languages include Cebuano, Ilocano, and Hiligaynon. This diversity reflects the rich history and migration patterns across the islands."},{"heading":"Why It Matters","body":"Understanding this helps us appreciate the rich culture and geography of the Philippines today."}],
    keyFacts: ["Filipino and English are the official languages of the Philippines.","Filipino is heavily based on the Tagalog language.","There are over 170 different languages spoken across the islands."],
    realWorldConnection: "Families today see the importance of The Filipino Language in their daily lives across the archipelago.",
    vocabulary: [{"word":"Wika","translation":"Language","language":"Tagalog","pronunciation":"WEE-kah"}],
    mediaMoments: [
      { description: "Visual related to The Filipino Language", purpose: "To show context visually", requiredType: "Photograph", sourceRequirement: "authoritative", altTextRequirement: true }
    ],
    guidedDiscussion: ["What is the most interesting thing you learned?", "How does this compare to where we live?", "Why is this important for the country?"],
    ageDifferentiation: { explorer: "Draw a picture related to the topic.", adventure: "Write two sentences explaining the main idea.", trailblazer: "Research an additional fact from an authoritative source and present it." },
    handsOnTask: { title: "Create a Mini-Project", materials: ["Paper", "Pencils", "Colors"], setup: "Gather your supplies.", steps: ["Draw the main subject.", "Label the key parts.", "Present it to your family."], finishCondition: "You have a completed drawing.", safetyNotes: "Use scissors carefully if needed.", alternative: "Discuss the topic aloud." },
    game: { title: "Fact Match", objective: "Match the fact to the correct term.", materials: ["Index cards"], setup: "Write vocabulary and facts on cards.", rules: "Flip two cards to find a match.", winCondition: "Match all pairs.", adaptation: "Play with fewer cards for younger explorers." },
    knowledgeCheck: [
      { question: "What is the main topic of today's lesson?", options: ["The Filipino Language", "Outer Space", "Ancient Rome", "Cooking"], correctAnswer: "The Filipino Language" },
      { question: "Which of the following is true?", options: ["Filipino and English are the official languages of the Philippines.", "The Philippines is in Europe.", "It snows heavily every winter.", "There are no islands."], correctAnswer: "Filipino and English are the official languages of the Philippines." },
      { question: "What is another important fact?", options: ["Filipino is heavily based on the Tagalog language.", "Penguins live there natively.", "It is entirely a desert.", "It has only one city."], correctAnswer: "Filipino is heavily based on the Tagalog language." },
      { question: "Who leads a province or region?", options: ["Local Government Leaders", "Kings", "Emperors", "Pharaohs"], correctAnswer: "Local Government Leaders" },
      { question: "Why is this topic important?", options: ["It shapes the culture and daily life.", "It is a secret.", "It does not matter.", "It is only for tourists."], correctAnswer: "It shapes the culture and daily life." }
    ],
    learnerReflection: "What did you find most surprising about The Filipino Language?",
    familyChallenge: "Share one fact from today's lesson with someone in your family.",
    teacherPreparation: "Review the key facts and vocabulary for The Filipino Language.",
    teacherAnswerKey: { q1: "The Filipino Language", q2: "Filipino and English are the official languages of the Philippines.", q3: "Filipino is heavily based on the Tagalog language.", q4: "Local Government Leaders", q5: "It shapes the culture and daily life." },
    authoritativeSources: [{"source":"Komisyon sa Wikang Filipino (KWF)","url":"https://kwf.gov.ph/","note":"Language statistics and history"}],
    curatedResources: [
      { id: "r1_lesson-12-language", title: "KWF: Komisyon sa Wikang Filipino", url: "https://kwf.gov.ph/", type: "Website" },
      { id: "r2_lesson-12-language", title: "NCCA: Languages of the Philippines", url: "https://ncca.gov.ph/about-culture-and-arts/culture-profile/", type: "Website" }
    ],
    privacyClassification: "family-safe",
    publicationStatus: "published",
    activities: { beginnerSupport: "Provide extra help.", coreActivity: "Standard activity.", advancedChallenge: "Extra research." },
    interactiveGame: "Fact Match",
    handsOnActivity: "Create a Mini-Project",
    materials: ["Paper", "Pencils"],
    factualMediaRequirements: ["media_1"],
    sourceNotes: "Verified via authoritative government sources.",
    mediaAttributionNotes: "Ensure all media used has appropriate educational licenses.",
    accessibilityNotes: "Provide auditory descriptions of visuals.",
    subjectConnections: {},
    progressBadge: "badge-id"
  },
  {
    id: "lesson-13-august-review",
    date: "2026-08-31",
    weekday: "Monday",
    title: "August Review and Showcase",
    topic: "Review",
    ageRange: "7-12",
    unit: "Unit 1: Our Island Home",
    learningObjectives: ["Understand the geography and culture related to August Review and Showcase", "Identify key facts", "Apply learning to daily life"],
    essentialQuestion: "What makes August Review and Showcase an important part of the Philippines?",
    factualBackground: "Throughout August, we explored the physical geography, political structure, and natural wonders of the Philippines. We learned that the 7,641 islands form three major groups (Luzon, Visayas, Mindanao) which are governed through 17 administrative regions, 82 provinces, and thousands of barangays. We also discovered endemic animals like the Philippine Eagle and important plants like the coconut tree.",
    adventureHook: "Are you ready to explore August Review and Showcase? Let's dive into the amazing facts of the Philippines!",
    discoveries: ["Fact 1", "Fact 2", "Fact 3"],
    richExplanation: [{"heading":"Introduction to Review","body":"Throughout August, we explored the physical geography, political structure, and natural wonders of the Philippines. We learned that the 7,641 islands form three major groups (Luzon, Visayas, Mindanao) which are governed through 17 administrative regions, 82 provinces, and thousands of barangays. We also discovered endemic animals like the Philippine Eagle and important plants like the coconut tree."},{"heading":"Why It Matters","body":"Understanding this helps us appreciate the rich culture and geography of the Philippines today."}],
    keyFacts: ["The Philippines is an archipelago of 7,641 islands.","It is divided into Luzon, Visayas, and Mindanao.","Barangays are the smallest local government units.","The Philippine Eagle and Sampaguita are unique natural treasures."],
    realWorldConnection: "Families today see the importance of August Review and Showcase in their daily lives across the archipelago.",
    vocabulary: [{"word":"Pilipinas","translation":"Philippines","language":"Tagalog","pronunciation":"pee-lee-PEE-nahs"}],
    mediaMoments: [
      { description: "Visual related to August Review and Showcase", purpose: "To show context visually", requiredType: "Photograph", sourceRequirement: "authoritative", altTextRequirement: true }
    ],
    guidedDiscussion: ["What is the most interesting thing you learned?", "How does this compare to where we live?", "Why is this important for the country?"],
    ageDifferentiation: { explorer: "Draw a picture related to the topic.", adventure: "Write two sentences explaining the main idea.", trailblazer: "Research an additional fact from an authoritative source and present it." },
    handsOnTask: { title: "Create a Mini-Project", materials: ["Paper", "Pencils", "Colors"], setup: "Gather your supplies.", steps: ["Draw the main subject.", "Label the key parts.", "Present it to your family."], finishCondition: "You have a completed drawing.", safetyNotes: "Use scissors carefully if needed.", alternative: "Discuss the topic aloud." },
    game: { title: "Fact Match", objective: "Match the fact to the correct term.", materials: ["Index cards"], setup: "Write vocabulary and facts on cards.", rules: "Flip two cards to find a match.", winCondition: "Match all pairs.", adaptation: "Play with fewer cards for younger explorers." },
    knowledgeCheck: [
      { question: "What is the main topic of today's lesson?", options: ["August Review and Showcase", "Outer Space", "Ancient Rome", "Cooking"], correctAnswer: "August Review and Showcase" },
      { question: "Which of the following is true?", options: ["The Philippines is an archipelago of 7,641 islands.", "The Philippines is in Europe.", "It snows heavily every winter.", "There are no islands."], correctAnswer: "The Philippines is an archipelago of 7,641 islands." },
      { question: "What is another important fact?", options: ["It is divided into Luzon, Visayas, and Mindanao.", "Penguins live there natively.", "It is entirely a desert.", "It has only one city."], correctAnswer: "It is divided into Luzon, Visayas, and Mindanao." },
      { question: "Who leads a province or region?", options: ["Local Government Leaders", "Kings", "Emperors", "Pharaohs"], correctAnswer: "Local Government Leaders" },
      { question: "Why is this topic important?", options: ["It shapes the culture and daily life.", "It is a secret.", "It does not matter.", "It is only for tourists."], correctAnswer: "It shapes the culture and daily life." }
    ],
    learnerReflection: "What did you find most surprising about August Review and Showcase?",
    familyChallenge: "Share one fact from today's lesson with someone in your family.",
    teacherPreparation: "Review the key facts and vocabulary for August Review and Showcase.",
    teacherAnswerKey: { q1: "August Review and Showcase", q2: "The Philippines is an archipelago of 7,641 islands.", q3: "It is divided into Luzon, Visayas, and Mindanao.", q4: "Local Government Leaders", q5: "It shapes the culture and daily life." },
    authoritativeSources: [{"source":"National Historical Commission of the Philippines (NHCP)","url":"https://nhcp.gov.ph/","note":"Historical summary"}],
    curatedResources: [
      { id: "r1_lesson-13-august-review", title: "National Museum: Geographic and Natural History", url: "https://www.nationalmuseum.gov.ph/", type: "Website" },
      { id: "r2_lesson-13-august-review", title: "NHCP: Philippine History Overview", url: "https://nhcp.gov.ph/history-of-the-philippines/", type: "Website" }
    ],
    privacyClassification: "family-safe",
    publicationStatus: "published",
    activities: { beginnerSupport: "Provide extra help.", coreActivity: "Standard activity.", advancedChallenge: "Extra research." },
    interactiveGame: "Fact Match",
    handsOnActivity: "Create a Mini-Project",
    materials: ["Paper", "Pencils"],
    factualMediaRequirements: ["media_1"],
    sourceNotes: "Verified via authoritative government sources.",
    mediaAttributionNotes: "Ensure all media used has appropriate educational licenses.",
    accessibilityNotes: "Provide auditory descriptions of visuals.",
    subjectConnections: {},
    progressBadge: "badge-id"
  }
];
