import { CurriculumLesson } from "@/lib/curriculum-schema";

export const stage6Lessons: CurriculumLesson[] = [
  {
    id: "lesson-40-kitchen-safety",
    date: "2026-11-02",
    weekday: "Monday",
    title: "Kitchen Safety and Basics",
    unit: "Filipino Cooking and Family Heritage",
    topic: "Kitchen safety",
    ageRange: "6-8",
    privacyClassification: "family-safe",
    publicationStatus: "pilot",
    learningObjectives: ["Identify age-appropriate kitchen safety, hygiene, and basic cooking tools."],
    essentialQuestion: "How do we stay safe in the kitchen?",
    factualBackground: "Safe cooking practices involve handwashing, distinguishing child-safe from adult-only tasks (e.g., using knives or the stove), and cleaning up spills.",
    vocabulary: [
      { word: "Kutsara", translation: "Spoon", language: "Tagalog", hiligaynon: "Kutsara" },
      { word: "Ligtas", translation: "Safe", language: "Tagalog", hiligaynon: "Hilway / Ligtas" }
    ],
    subjectConnections: { cooking: "Kitchen Safety" },
    materials: ["Kitchen safety flashcards"],
    factualMediaRequirements: ["kitchen-safety-illustration"],
    mediaReferences: ["kitchen-safety-illustration"],
    activities: {
      beginnerSupport: "Point to the adult in the picture.",
      coreActivity: "Sort tasks into CHILD-SAFE and ADULT-ONLY groups.",
      advancedChallenge: "Draw a picture of washing hands."
    },
    interactiveGame: "Safety Sort",
    handsOnActivity: "Practice washing produce with adult guidance. (No-food alternative: play with toy utensils)",
    knowledgeCheck: [{ question: "Is using a knife a child-safe task?", options: ["No, it is adult-only", "Yes"], correctAnswer: "No, it is adult-only" }],
    learnerReflection: "I know how to be safe.",
    familyChallenge: "Review kitchen safety rules with your family.",
    progressBadge: "Kitchen Helper",
    sourceNotes: "FDA Food Safety Guidelines, Tagalog/Hiligaynon verified via KWF",
    mediaAttributionNotes: "Illustration of kitchen safety",
    accessibilityNotes: "Clear visuals for sorting game",
    teacherPreparation: "Review safety guidelines and allergy protocols. (Optional: Lead a prayer of thanks for provision.)",
    teacherAnswerKey: { "Q1": "No, it is adult-only" }
  },
  {
    id: "lesson-41-measurements",
    date: "2026-11-03",
    weekday: "Tuesday",
    title: "Measuring Ingredients",
    unit: "Filipino Cooking and Family Heritage",
    topic: "Measurements",
    ageRange: "6-8",
    privacyClassification: "family-safe",
    publicationStatus: "pilot",
    learningObjectives: ["Distinguish volume, mass, and common metric kitchen measurements through safe hands-on practice."],
    essentialQuestion: "How do we measure ingredients accurately?",
    factualBackground: "Recipes use specific measurements like cups, tablespoons, or grams to ensure consistent results.",
    vocabulary: [
      { word: "Sukatin", translation: "Measure", language: "Tagalog", hiligaynon: "Sukbon / Takson" },
      { word: "Kutsarita", translation: "Teaspoon", language: "Tagalog", hiligaynon: "Kutsarita" }
    ],
    subjectConnections: { cooking: "Measurements" },
    materials: ["Measuring cups", "Measuring spoons", "Water or dried beans for practice"],
    factualMediaRequirements: ["measuring-tools-photo"],
    mediaReferences: ["measuring-tools-photo"],
    activities: {
      beginnerSupport: "Hold the measuring spoon.",
      coreActivity: "Practice measuring dry beans or water with cups and spoons.",
      advancedChallenge: "Count how many teaspoons make a tablespoon."
    },
    interactiveGame: "Measurement Match",
    handsOnActivity: "Measure cool ingredients like water or rice. (No-food alternative: measure sand or beads)",
    knowledgeCheck: [{ question: "Which is bigger, a cup or a teaspoon?", options: ["Cup", "Teaspoon"], correctAnswer: "Cup" }],
    learnerReflection: "I can measure carefully.",
    familyChallenge: "Find measuring tools in your kitchen.",
    progressBadge: "Measurement Master",
    sourceNotes: "Standard kitchen measurement conversions, Tagalog/Hiligaynon verified via KWF",
    mediaAttributionNotes: "Verified photo of measuring tools",
    accessibilityNotes: "Tactile measuring tools",
    teacherPreparation: "Set up measuring stations.",
    teacherAnswerKey: { "Q1": "Cup" }
  },
  {
    id: "lesson-42-nutrition",
    date: "2026-11-06",
    weekday: "Friday",
    title: "Nourishing Filipino Ingredients",
    unit: "Filipino Cooking and Family Heritage",
    topic: "Nutrition",
    ageRange: "6-8",
    privacyClassification: "family-safe",
    publicationStatus: "pilot",
    learningObjectives: ["Identify common Filipino fruits and vegetables and describe how varied foods contribute to balanced meals without making medical or weight-related claims."],
    essentialQuestion: "Why is it important to eat a variety of foods?",
    factualBackground: "Eating different kinds of foods, like vegetables and fruits, helps provide the body with energy and nutrients for daily activities.",
    vocabulary: [
      { word: "Gulay", translation: "Vegetables", language: "Tagalog", hiligaynon: "Utan" },
      { word: "Prutas", translation: "Fruit", language: "Tagalog", hiligaynon: "Prutas" }
    ],
    subjectConnections: { science: "Nutrition" },
    materials: ["Photos of local vegetables and fruits"],
    factualMediaRequirements: ["filipino-vegetables-photo"],
    mediaReferences: ["filipino-vegetables-photo"],
    activities: {
      beginnerSupport: "Point to a vegetable.",
      coreActivity: "Sort pictures into fruits and vegetables.",
      advancedChallenge: "Draw a balanced meal."
    },
    interactiveGame: "Food Match",
    handsOnActivity: "Make a collage of local foods. (No-food activity)",
    knowledgeCheck: [{ question: "Do vegetables give us energy?", options: ["Yes", "No"], correctAnswer: "Yes" }],
    learnerReflection: "I like colorful foods.",
    familyChallenge: "Identify one vegetable during dinner.",
    progressBadge: "Nutrition Explorer",
    sourceNotes: "FNRI-DOST pinggang pinoy guidelines, Tagalog/Hiligaynon verified via KWF",
    mediaAttributionNotes: "Verified photo of vegetables",
    accessibilityNotes: "High contrast images",
    teacherPreparation: "Review Pinggang Pinoy guidelines to avoid medical claims.",
    teacherAnswerKey: { "Q1": "Yes" }
  },
  {
    id: "lesson-43-rice-basics",
    date: "2026-11-09",
    weekday: "Monday",
    title: "Rice in Filipino Meals",
    unit: "Filipino Cooking and Family Heritage",
    topic: "Cooking Rice",
    ageRange: "6-8",
    privacyClassification: "family-safe",
    publicationStatus: "pilot",
    learningObjectives: ["Explain the cultural role of rice and observe an adult-led safe preparation process."],
    essentialQuestion: "How is rice prepared for our meals?",
    factualBackground: "Rice is a staple food in the Philippines, eaten with almost every meal, and is often cooked in a rice cooker or pot.",
    vocabulary: [
      { word: "Bigas", translation: "Uncooked rice", language: "Tagalog", hiligaynon: "Bugay / Bugas" },
      { word: "Kanin", translation: "Cooked rice", language: "Tagalog", hiligaynon: "Kan-on" }
    ],
    subjectConnections: { culture: "Food Staples" },
    materials: ["Rice grains"],
    factualMediaRequirements: ["cooking-rice-photo"],
    mediaReferences: ["cooking-rice-photo"],
    activities: {
      beginnerSupport: "Touch dry rice grains.",
      coreActivity: "Observe the adult safely washing and cooking rice.",
      advancedChallenge: "Explain the difference between bigas and kanin."
    },
    interactiveGame: "Rice Steps Sort",
    handsOnActivity: "Help wash rice (CHILD-SAFE). The adult handles the hot rice cooker (ADULT-ONLY).",
    knowledgeCheck: [{ question: "Who should handle the hot rice cooker?", options: ["Adult only", "Child"], correctAnswer: "Adult only" }],
    learnerReflection: "Rice is important in our meals.",
    familyChallenge: "Observe how rice is cooked at home.",
    progressBadge: "Rice Helper",
    sourceNotes: "Cultural observation, Tagalog/Hiligaynon verified via KWF",
    mediaAttributionNotes: "Verified photo of rice",
    accessibilityNotes: "Tactile dry rice",
    teacherPreparation: "Prepare rice cooker and safety boundaries.",
    teacherAnswerKey: { "Q1": "Adult only" }
  },
  {
    id: "lesson-44-adobo-history",
    date: "2026-11-10",
    weekday: "Tuesday",
    title: "Adobo Across Filipino Kitchens",
    unit: "Filipino Cooking and Family Heritage",
    topic: "Adobo",
    ageRange: "6-8",
    privacyClassification: "family-safe",
    publicationStatus: "pilot",
    learningObjectives: ["Recognize common features and family or regional variations of Filipino adobo without presenting one recipe as definitive."],
    essentialQuestion: "Why are there so many ways to cook Adobo?",
    factualBackground: "Filipino adobo includes many vinegar-based preparations, with the Spanish term applied during the colonial period; variations exist across regions and families.",
    vocabulary: [
      { word: "Suka", translation: "Vinegar", language: "Tagalog", hiligaynon: "Langgaw" },
      { word: "Bawang", translation: "Garlic", language: "Tagalog", hiligaynon: "Ahos" }
    ],
    subjectConnections: { history: "Food History" },
    materials: ["Adobo recipe from /cooking/chicken-adobo"],
    factualMediaRequirements: ["adobo-variations-photo"],
    mediaReferences: ["adobo-variations-photo"],
    activities: {
      beginnerSupport: "Smell vinegar safely.",
      coreActivity: "Read the Chicken Adobo recipe guide (/cooking/chicken-adobo) and discuss variations.",
      advancedChallenge: "Name three ingredients in Adobo."
    },
    interactiveGame: "Adobo Ingredient Match",
    handsOnActivity: "CHILD-SAFE: Count garlic cloves. ADULT-ONLY: Stovetop cooking and raw meat handling.",
    knowledgeCheck: [{ question: "Do all families cook Adobo exactly the same way?", options: ["Yes", "No"], correctAnswer: "No" }],
    learnerReflection: "Every family has a special recipe.",
    familyChallenge: "Ask how your family cooks Adobo.",
    progressBadge: "Adobo Explorer",
    sourceNotes: "NCCA culinary history, Tagalog/Hiligaynon verified via KWF",
    mediaAttributionNotes: "Verified photo of adobo",
    accessibilityNotes: "Clear text",
    teacherPreparation: "Review adobo variations to avoid claiming one definitive version.",
    teacherAnswerKey: { "Q1": "No" }
  },
  {
    id: "lesson-45-sinigang-flavors",
    date: "2026-11-13",
    weekday: "Friday",
    title: "Sinigang and Sour Flavors",
    unit: "Filipino Cooking and Family Heritage",
    topic: "Sinigang",
    ageRange: "6-8",
    privacyClassification: "family-safe",
    publicationStatus: "pilot",
    learningObjectives: ["Explore examples of souring ingredients and recognize that sinigang varies across regions and families."],
    essentialQuestion: "What makes Sinigang taste sour?",
    factualBackground: "Sinigang is a sour soup that can use different souring agents like tamarind, guava, or calamansi, depending on family or regional preference.",
    vocabulary: [
      { word: "Maasim", translation: "Sour", language: "Tagalog", hiligaynon: "Maaslom" },
      { word: "Sabaw", translation: "Soup/Broth", language: "Tagalog", hiligaynon: "Sabaw" }
    ],
    subjectConnections: { science: "Taste" },
    materials: ["Pictures of tamarind and calamansi"],
    factualMediaRequirements: ["sinigang-photo"],
    mediaReferences: ["sinigang-photo"],
    activities: {
      beginnerSupport: "Say Maasim.",
      coreActivity: "Identify different souring agents from pictures.",
      advancedChallenge: "Draw a bowl of Sinigang."
    },
    interactiveGame: "Sour Match",
    handsOnActivity: "CHILD-SAFE: Sort pictures of souring agents. ADULT-ONLY: Boiling water and slicing.",
    knowledgeCheck: [{ question: "Is tamarind the only ingredient that can make Sinigang sour?", options: ["Yes", "No"], correctAnswer: "No" }],
    learnerReflection: "I know what sour means.",
    familyChallenge: "Taste a drop of calamansi or lemon.",
    progressBadge: "Flavor Explorer",
    sourceNotes: "NCCA culinary history, Tagalog/Hiligaynon verified via KWF",
    mediaAttributionNotes: "Verified photo of sinigang",
    accessibilityNotes: "High contrast images",
    teacherPreparation: "Prepare souring agent examples.",
    teacherAnswerKey: { "Q1": "No" }
  },
  {
    id: "lesson-46-pancit-celebration",
    date: "2026-11-16",
    weekday: "Monday",
    title: "Pancit and Celebration Traditions",
    unit: "Filipino Cooking and Family Heritage",
    topic: "Pancit",
    ageRange: "6-8",
    privacyClassification: "family-safe",
    publicationStatus: "pilot",
    learningObjectives: ["Explain the cultural association between noodles, long life, birthdays, and some Filipino celebrations without treating it as a health claim or universal practice."],
    essentialQuestion: "Why do some people serve noodles at birthdays?",
    factualBackground: "In many Filipino celebrations, noodles represent a cultural wish for a long and blessed life.",
    vocabulary: [
      { word: "Pancit", translation: "Noodles", language: "Tagalog", hiligaynon: "Pansit / Pancit" },
      { word: "Handaan", translation: "Celebration/Feast", language: "Tagalog", hiligaynon: "Punsyon" }
    ],
    subjectConnections: { culture: "Celebrations" },
    materials: ["Pancit recipe from /cooking/pancit"],
    factualMediaRequirements: ["pancit-photo"],
    mediaReferences: ["pancit-photo"],
    activities: {
      beginnerSupport: "Draw long noodles.",
      coreActivity: "Read the Pancit recipe guide (/cooking/pancit) and discuss celebration traditions.",
      advancedChallenge: "Write a birthday wish."
    },
    interactiveGame: "Noodle Match",
    handsOnActivity: "CHILD-SAFE: Soak noodles. ADULT-ONLY: Hot wok and knife work.",
    knowledgeCheck: [{ question: "Do noodles magically make you live longer?", options: ["Yes", "No, it is just a cultural symbol"], correctAnswer: "No, it is just a cultural symbol" }],
    learnerReflection: "I like learning about traditions.",
    familyChallenge: "Ask about your family's birthday traditions.",
    progressBadge: "Tradition Explorer",
    sourceNotes: "Cultural observation, Tagalog/Hiligaynon verified via KWF",
    mediaAttributionNotes: "Verified photo of pancit",
    accessibilityNotes: "Clear visuals",
    teacherPreparation: "Review pancit recipe to avoid health claims.",
    teacherAnswerKey: { "Q1": "No, it is just a cultural symbol" }
  },
  {
    id: "lesson-47-halo-halo",
    date: "2026-11-17",
    weekday: "Tuesday",
    title: "Halo-halo: Many Ingredients, Many Versions",
    unit: "Filipino Cooking and Family Heritage",
    topic: "Halo-halo",
    ageRange: "6-8",
    privacyClassification: "family-safe",
    publicationStatus: "pilot",
    learningObjectives: ["Identify common components of halo-halo while appreciating regional and family variations."],
    essentialQuestion: "What makes Halo-halo special?",
    factualBackground: "Halo-halo means 'mix-mix' and is a popular cold dessert made of shaved ice and varied sweet toppings, which differ by region.",
    vocabulary: [
      { word: "Halo-halo", translation: "Mix-mix", language: "Tagalog", hiligaynon: "Halo-halo" },
      { word: "Yelo", translation: "Ice", language: "Tagalog", hiligaynon: "Yelo" }
    ],
    subjectConnections: { culture: "Desserts" },
    materials: ["Halo-halo recipe from /cooking/halo-halo"],
    factualMediaRequirements: ["halo-halo-photo"],
    mediaReferences: ["halo-halo-photo"],
    activities: {
      beginnerSupport: "Pretend to mix ice.",
      coreActivity: "Read the Halo-halo recipe guide (/cooking/halo-halo) and design a paper version.",
      advancedChallenge: "Name 4 ingredients in Halo-halo."
    },
    interactiveGame: "Ingredient Match",
    handsOnActivity: "CHILD-SAFE: Layer sweet ingredients. ADULT-ONLY: Crushing ice with a blender.",
    knowledgeCheck: [{ question: "Is there only one way to make Halo-halo?", options: ["Yes", "No"], correctAnswer: "No" }],
    learnerReflection: "I like mixing things.",
    familyChallenge: "Draw your perfect Halo-halo.",
    progressBadge: "Dessert Explorer",
    sourceNotes: "Cultural observation, Tagalog/Hiligaynon verified via KWF",
    mediaAttributionNotes: "Verified photo of halo-halo",
    accessibilityNotes: "Clear text",
    teacherPreparation: "Review halo-halo recipe.",
    teacherAnswerKey: { "Q1": "No" }
  },
  {
    id: "lesson-48-mango-float",
    date: "2026-11-20",
    weekday: "Friday",
    title: "Mango Float: A Family No-Bake Dessert",
    unit: "Filipino Cooking and Family Heritage",
    topic: "Mango Float",
    ageRange: "6-8",
    privacyClassification: "family-safe",
    publicationStatus: "pilot",
    learningObjectives: ["Safely assemble a simple chilled dessert with adult supervision and allergy awareness."],
    essentialQuestion: "How do we make a dessert without baking?",
    factualBackground: "Mango float is a no-bake layered dessert made with graham crackers, cream, and mangoes, chilled to set.",
    vocabulary: [
      { word: "Mangga", translation: "Mango", language: "Tagalog", hiligaynon: "Paho" },
      { word: "Matamis", translation: "Sweet", language: "Tagalog", hiligaynon: "Matam-is" }
    ],
    subjectConnections: { cooking: "Food Prep" },
    materials: ["Mango float recipe from /cooking/mango-float"],
    factualMediaRequirements: ["mango-float-photo"],
    mediaReferences: ["mango-float-photo"],
    activities: {
      beginnerSupport: "Say Mangga.",
      coreActivity: "Review the Mango Float guide (/cooking/mango-float) and practice layering crackers safely.",
      advancedChallenge: "Write down the layers in order."
    },
    interactiveGame: "Layering Game",
    handsOnActivity: "CHILD-SAFE: Layering crackers and cream. ADULT-ONLY: Slicing mangoes with a knife.",
    knowledgeCheck: [{ question: "Who should slice the mangoes with a knife?", options: ["Adult only", "Child"], correctAnswer: "Adult only" }],
    learnerReflection: "I can help make dessert safely.",
    familyChallenge: "Make a mango float together (with allergy awareness).",
    progressBadge: "No-Bake Master",
    sourceNotes: "Culinary safety, Tagalog/Hiligaynon verified via KWF",
    mediaAttributionNotes: "Verified photo of mango float",
    accessibilityNotes: "Clear audio instructions",
    teacherPreparation: "Review existing mango float recipe and allergy protocols (dairy).",
    teacherAnswerKey: { "Q1": "Adult only" }
  },
  {
    id: "lesson-49-kakanin",
    date: "2026-11-23",
    weekday: "Monday",
    title: "Kakanin: Rice-Based Delicacies",
    unit: "Filipino Cooking and Family Heritage",
    topic: "Kakanin",
    ageRange: "6-8",
    privacyClassification: "family-safe",
    publicationStatus: "pilot",
    learningObjectives: ["Compare selected rice-based delicacies while respecting regional names, ingredients, and preparation differences."],
    essentialQuestion: "What is Kakanin?",
    factualBackground: "Kakanin refers to a broad category of Filipino sweet delicacies typically made from glutinous rice and coconut milk.",
    vocabulary: [
      { word: "Kakanin", translation: "Rice delicacy", language: "Tagalog", hiligaynon: "Kakanin" },
      { word: "Niyog", translation: "Coconut", language: "Tagalog", hiligaynon: "Lubi" }
    ],
    subjectConnections: { culture: "Sweets" },
    materials: ["Pictures of puto and suman"],
    factualMediaRequirements: ["kakanin-photo"],
    mediaReferences: ["kakanin-photo"],
    activities: {
      beginnerSupport: "Point to the coconut.",
      coreActivity: "Look at different kakanin pictures and notice their shapes.",
      advancedChallenge: "Explain what ingredient is common in Kakanin."
    },
    interactiveGame: "Kakanin Match",
    handsOnActivity: "Mold clay into Kakanin shapes. (No-food alternative)",
    knowledgeCheck: [{ question: "Is Kakanin made of rice?", options: ["Yes", "No"], correctAnswer: "Yes" }],
    learnerReflection: "I learned about rice sweets.",
    familyChallenge: "Ask your family what their favorite Kakanin is.",
    progressBadge: "Kakanin Expert",
    sourceNotes: "NCCA cultural records, Tagalog/Hiligaynon verified via KWF",
    mediaAttributionNotes: "Verified photo of kakanin",
    accessibilityNotes: "High contrast visuals",
    teacherPreparation: "Prepare clay.",
    teacherAnswerKey: { "Q1": "Yes" }
  },
  {
    id: "lesson-50-grandmas-recipe-box",
    date: "2026-11-24",
    weekday: "Tuesday",
    title: "Our Family Recipe Box",
    unit: "Filipino Cooking and Family Heritage",
    topic: "Family Recipes",
    ageRange: "6-8",
    privacyClassification: "family-safe",
    publicationStatus: "pilot",
    learningObjectives: ["Recognize how parents, grandparents, guardians, and other family members pass recipes and food memories between generations."],
    essentialQuestion: "How do we keep our favorite recipes?",
    factualBackground: "Families preserve their heritage by passing down recipes, stories, and traditions across generations.",
    vocabulary: [
      { word: "Pamilya", translation: "Family", language: "Tagalog", hiligaynon: "Pamilya" },
      { word: "Pagkain", translation: "Food", language: "Tagalog", hiligaynon: "Pagkaon" }
    ],
    subjectConnections: { history: "Family History" },
    materials: ["Blank recipe cards"],
    factualMediaRequirements: ["recipe-box-photo"],
    mediaReferences: ["recipe-box-photo"],
    activities: {
      beginnerSupport: "Draw a favorite food.",
      coreActivity: "Design a recipe card for a family favorite dish (using fictional or general examples if preferred).",
      advancedChallenge: "Write why this food is special to your family."
    },
    interactiveGame: "Recipe Match",
    handsOnActivity: "Decorate a recipe box. (CHILD-SAFE)",
    knowledgeCheck: [{ question: "Can anyone in the family preserve recipes?", options: ["Yes", "No"], correctAnswer: "Yes" }],
    learnerReflection: "I love our family recipes.",
    familyChallenge: "Write down one family recipe (no personal details required).",
    progressBadge: "Recipe Keeper",
    sourceNotes: "General heritage, Tagalog/Hiligaynon verified via KWF",
    mediaAttributionNotes: "Verified photo of a recipe box",
    accessibilityNotes: "Large text options",
    teacherPreparation: "Provide privacy-safe guidelines for sharing.",
    teacherAnswerKey: { "Q1": "Yes" }
  },
  {
    id: "lesson-51-family-heritage-wall",
    date: "2026-11-27",
    weekday: "Friday",
    title: "Family Heritage Wall",
    unit: "Filipino Cooking and Family Heritage",
    topic: "Heritage",
    ageRange: "6-8",
    privacyClassification: "family-safe",
    publicationStatus: "pilot",
    learningObjectives: ["Create a privacy-safe representation of family food traditions and cultural heritage."],
    essentialQuestion: "How can we celebrate our family's heritage safely?",
    factualBackground: "Celebrating heritage can be done through art, stories, and symbols without exposing private personal information.",
    vocabulary: [
      { word: "Kuwento", translation: "Story", language: "Tagalog", hiligaynon: "Sugilanon" },
      { word: "Salamat", translation: "Thank you", language: "Tagalog", hiligaynon: "Salamat" }
    ],
    subjectConnections: { art: "Heritage" },
    materials: ["Paper, crayons"],
    factualMediaRequirements: ["heritage-art-photo"],
    mediaReferences: ["heritage-art-photo"],
    activities: {
      beginnerSupport: "Draw a happy face.",
      coreActivity: "Create a drawing or symbol representing a family tradition (privacy-safe).",
      advancedChallenge: "Present your drawing to the class."
    },
    interactiveGame: "Heritage Match",
    handsOnActivity: "Build a class heritage wall with drawings.",
    knowledgeCheck: [{ question: "Should we share private addresses on our heritage wall?", options: ["No", "Yes"], correctAnswer: "No" }],
    learnerReflection: "I am proud of my heritage.",
    familyChallenge: "Make a family heritage poster at home.",
    progressBadge: "Heritage Artist",
    sourceNotes: "Privacy guidelines, Tagalog/Hiligaynon verified via KWF",
    mediaAttributionNotes: "Verified photo of art",
    accessibilityNotes: "Clear visuals",
    teacherPreparation: "Ensure all submissions are privacy-safe.",
    teacherAnswerKey: { "Q1": "No" }
  },
  {
    id: "lesson-52-november-showcase",
    date: "2026-11-30",
    weekday: "Monday",
    title: "November Food and Heritage Showcase",
    unit: "Filipino Cooking and Family Heritage",
    topic: "Showcase",
    ageRange: "6-8",
    privacyClassification: "family-safe",
    publicationStatus: "pilot",
    learningObjectives: ["Review November learning and optionally share a privacy-safe family food memory, illustration, or fictional example."],
    essentialQuestion: "What did we learn about Filipino cooking and heritage?",
    factualBackground: "A showcase allows us to reflect on our learning journey about kitchen safety, nutrition, recipes, and family heritage.",
    vocabulary: [],
    subjectConnections: { culture: "November Review" },
    materials: ["Learner portfolios"],
    factualMediaRequirements: [],
    activities: {
      beginnerSupport: "Show one drawing.",
      coreActivity: "Present a privacy-safe food memory or drawing.",
      advancedChallenge: "Explain what kitchen safety means."
    },
    interactiveGame: "Cooking Review Quiz",
    handsOnActivity: "Organize the portfolio.",
    knowledgeCheck: [{ question: "Is it important to wash hands before cooking?", options: ["Yes", "No"], correctAnswer: "Yes" }],
    learnerReflection: "I learned a lot this month.",
    familyChallenge: "Show your family what you learned.",
    progressBadge: "November Chef",
    sourceNotes: "Review, no new claims",
    mediaAttributionNotes: "None",
    accessibilityNotes: "Clear audio",
    teacherPreparation: "Prepare for showcase and privacy checks.",
    teacherAnswerKey: { "Q1": "Yes" }
  }
];
