import { CurriculumLesson } from '@/lib/curriculum-schema';

export const stage2Lessons: CurriculumLesson[] = [
  {
    id: "lesson-1-world-map",
    date: "2026-08-03",
    weekday: "Monday",
    title: "World Map → Asia → Philippines",
    topic: "Philippine geography",
    ageRange: "6-8",
    unit: "Discover the Philippines",
    learningObjectives: ["Locate the Philippines on a world map", "Identify Southeast Asia"],
    essentialQuestion: "Where in the world is the Philippines?",
    factualBackground: "The Philippines is located in Southeast Asia.",
    vocabulary: [{ word: "Pilipinas", translation: "Philippines" }],
    subjectConnections: { geography: "World Maps" },
    materials: ["Globe or World Map"],
    factualMediaRequirements: ["world-map-asia", "philippines-hero"],
    mediaReferences: ["world-map-asia", "philippines-hero"],
    factualSources: [
      {
        source: "CIA World Factbook",
        url: "https://www.cia.gov/the-world-factbook/countries/philippines/",
        note: "Verified country location and continental region."
      }
    ],
    activities: {
      beginnerSupport: "Point to the Philippines on the map.",
      coreActivity: "Find the Philippines and trace the route from our home country.",
      advancedChallenge: "Name three countries that neighbor the Philippines."
    },
    interactiveGame: "Map Match",
    handsOnActivity: "Draw your own map",
    knowledgeCheck: [
      { question: "What continent is the Philippines in?", options: ["Asia", "Europe"], correctAnswer: "Asia" }
    ],
    learnerReflection: "I learned where the Philippines is located.",
    familyChallenge: "Show your family where the Philippines is on a map.",
    progressBadge: "World Explorer",
    sourceNotes: "CIA World Factbook",
    mediaAttributionNotes: "Maps pending verification",
    accessibilityNotes: "Provide high contrast maps.",
    privacyClassification: "family-safe",
    publicationStatus: "pilot",
    teacherPreparation: "Review world map and find the Philippines beforehand.",
    teacherAnswerKey: { "Q1": "Asia" }
  },
  {
    id: "lesson-2-archipelago",
    date: "2026-08-04",
    weekday: "Tuesday",
    title: "The Philippines as an Archipelago",
    topic: "Philippine geography",
    ageRange: "6-8",
    unit: "Discover the Philippines",
    learningObjectives: ["Understand the definition of archipelago"],
    essentialQuestion: "What is an archipelago?",
    factualBackground: "An archipelago is a group of islands. The Philippines has 7,641 islands.",
    vocabulary: [{ word: "Isla", translation: "Island" }],
    subjectConnections: { geography: "Islands" },
    materials: ["Map of the Philippines"],
    factualMediaRequirements: ["philippines-archipelago-map", "philippines-archipelago-photo"],
    mediaReferences: ["philippines-archipelago-map", "philippines-archipelago-photo"],
    factualSources: [
      {
        source: "NAMRIA",
        url: "https://www.namria.gov.ph/",
        note: "Philippine mapping authority for geographic and island count data."
      }
    ],
    activities: {
      beginnerSupport: "Count islands on the map.",
      coreActivity: "Define archipelago and identify the Philippines as one.",
      advancedChallenge: "Research how archipelagos are formed."
    },
    interactiveGame: "Island Hopper",
    handsOnActivity: "Clay island modeling",
    knowledgeCheck: [
      { question: "What is a group of islands called?", options: ["Archipelago", "Peninsula"], correctAnswer: "Archipelago" }
    ],
    learnerReflection: "I learned what an archipelago is.",
    familyChallenge: "Build a tiny archipelago at home using pillows.",
    progressBadge: "Island Explorer",
    sourceNotes: "NAMRIA",
    mediaAttributionNotes: "Maps pending verification",
    accessibilityNotes: "Tactile maps for visually impaired.",
    privacyClassification: "family-safe",
    publicationStatus: "pilot",
    teacherPreparation: "Prepare clay for modeling.",
    teacherAnswerKey: { "Q1": "Archipelago" }
  },
  {
    id: "lesson-3-luzon-visayas-mindanao",
    date: "2026-08-07",
    weekday: "Friday",
    title: "Luzon, Visayas, and Mindanao",
    topic: "Philippine geography",
    ageRange: "6-8",
    unit: "Discover the Philippines",
    learningObjectives: ["Identify the three main island groups"],
    essentialQuestion: "What are the three main regions of the Philippines?",
    factualBackground: "Luzon, Visayas, and Mindanao are the three major island groups.",
    vocabulary: [{ word: "Luzon", translation: "Luzon" }, { word: "Visayas", translation: "Visayas" }, { word: "Mindanao", translation: "Mindanao" }],
    subjectConnections: { geography: "Philippine Regions" },
    materials: ["Philippine Regions Map"],
    factualMediaRequirements: ["philippines-regions-map", "philippines-regions-photo"],
    mediaReferences: ["philippines-regions-map", "philippines-regions-photo"],
    factualSources: [
      {
        source: "Philippine Statistics Authority",
        url: "https://psa.gov.ph/",
        note: "Official statistics and regional information for the Philippines."
      }
    ],
    activities: {
      beginnerSupport: "Color the three regions.",
      coreActivity: "Learn the names of the three major island groups.",
      advancedChallenge: "Identify one major city in each region."
    },
    interactiveGame: "Region Match",
    handsOnActivity: "Region puzzle",
    knowledgeCheck: [
      { question: "Which is a major island group?", options: ["Luzon", "Hawaii"], correctAnswer: "Luzon" }
    ],
    learnerReflection: "I learned the three main island groups.",
    familyChallenge: "Sing a song about Luzon, Visayas, and Mindanao.",
    progressBadge: "Region Master",
    sourceNotes: "Philippine Statistics Authority",
    mediaAttributionNotes: "Maps pending verification",
    accessibilityNotes: "Color-blind friendly maps.",
    privacyClassification: "family-safe",
    publicationStatus: "pilot",
    teacherPreparation: "Print region puzzle pieces.",
    teacherAnswerKey: { "Q1": "Luzon" }
  },

  {
    id: "lesson-4-region",
    date: "2026-08-10",
    weekday: "Monday",
    title: "Exploring Our Region",
    topic: "Philippine geography",
    ageRange: "6-8",
    unit: "Discover the Philippines",
    learningObjectives: ["Understand what a region is"],
    essentialQuestion: "What region are we exploring?",
    factualBackground: "The Philippines is divided into 17 administrative regions.",
    vocabulary: [{ word: "Rehiyon", translation: "Region", language: "Tagalog", hiligaynon: "Rehiyon" }],
    subjectConnections: { geography: "Regions" },
    materials: ["Map of regions"],
    factualMediaRequirements: ["philippines-regions-map"],
    mediaReferences: ["philippines-regions-map"],
    factualSources: [{ source: "PSA", note: "Verified 17 administrative regions" }],
    activities: {
      beginnerSupport: "Point to a region.",
      coreActivity: "Find our target region on the map.",
      advancedChallenge: "Name 3 regions in the Philippines."
    },
    interactiveGame: "Region Match",
    handsOnActivity: "Color the region",
    knowledgeCheck: [
      { question: "How many regions are there?", options: ["17", "50"], correctAnswer: "17" }
    ],
    learnerReflection: "I learned about regions.",
    familyChallenge: "Discuss your family's home region.",
    progressBadge: "Region Explorer",
    sourceNotes: "PSA, verified Tagalog/Hiligaynon from KWF",
    mediaAttributionNotes: "Map verified",
    accessibilityNotes: "High contrast",
    privacyClassification: "family-safe",
    publicationStatus: "pilot",
    teacherPreparation: "Review regional map.",
    teacherAnswerKey: { "Q1": "17" }
  },
  {
    id: "lesson-5-province",
    date: "2026-08-11",
    weekday: "Tuesday",
    title: "Our Home Province",
    topic: "Philippine geography",
    ageRange: "6-8",
    unit: "Discover the Philippines",
    learningObjectives: ["Learn about provinces"],
    essentialQuestion: "What is a province?",
    factualBackground: "There are 82 provinces in the Philippines.",
    vocabulary: [{ word: "Lalawigan", translation: "Province", language: "Tagalog", hiligaynon: "Probinsya" }],
    subjectConnections: { geography: "Provinces" },
    materials: ["Map of provinces"],
    factualMediaRequirements: [],
    factualSources: [{ source: "PSA", note: "Verified 82 provinces" }],
    activities: {
      beginnerSupport: "Say the word province.",
      coreActivity: "Locate a province on the map.",
      advancedChallenge: "Identify the capital of the province."
    },
    interactiveGame: "Province Puzzle",
    handsOnActivity: "Draw the province shape",
    knowledgeCheck: [
      { question: "What is the Tagalog word for province?", options: ["Lalawigan", "Bayan"], correctAnswer: "Lalawigan" }
    ],
    learnerReflection: "I learned what a province is.",
    familyChallenge: "Ask your parents about their home province.",
    progressBadge: "Province Guide",
    sourceNotes: "PSA, verified Tagalog/Hiligaynon from KWF",
    mediaAttributionNotes: "None",
    accessibilityNotes: "Clear text",
    privacyClassification: "family-safe",
    publicationStatus: "pilot",
    teacherPreparation: "Prepare province map.",
    teacherAnswerKey: { "Q1": "Lalawigan" }
  },
  {
    id: "lesson-6-city",
    date: "2026-08-14",
    weekday: "Friday",
    title: "Our City and Hometown",
    topic: "Philippine geography",
    ageRange: "6-8",
    unit: "Discover the Philippines",
    learningObjectives: ["Identify a city or hometown"],
    essentialQuestion: "What makes our city special?",
    factualBackground: "Cities and municipalities make up a province.",
    vocabulary: [{ word: "Lungsod", translation: "City", language: "Tagalog", hiligaynon: "Syudad" }],
    subjectConnections: { geography: "Cities" },
    materials: ["Photos of hometown"],
    factualMediaRequirements: [],
    factualSources: [{ source: "LGC", note: "Verified cities and municipalities make up a province" }],
    activities: {
      beginnerSupport: "Name your city.",
      coreActivity: "Draw your favorite spot in the city.",
      advancedChallenge: "Write a sentence about your city."
    },
    interactiveGame: "City Bingo",
    handsOnActivity: "Build a mini city from blocks",
    knowledgeCheck: [
      { question: "What is the Tagalog word for city?", options: ["Lungsod", "Barangay"], correctAnswer: "Lungsod" }
    ],
    learnerReflection: "I love my city.",
    familyChallenge: "Take a walk in your city.",
    progressBadge: "City Explorer",
    sourceNotes: "Local Government Code, verified Tagalog/Hiligaynon from KWF",
    mediaAttributionNotes: "None",
    accessibilityNotes: "Clear audio",
    privacyClassification: "family-safe",
    publicationStatus: "pilot",
    teacherPreparation: "Gather hometown pictures.",
    teacherAnswerKey: { "Q1": "Lungsod" }
  },
  {
    id: "lesson-7-national-symbols",
    date: "2026-08-17",
    weekday: "Monday",
    title: "National Symbols",
    topic: "Philippine national symbols",
    ageRange: "6-8",
    unit: "Discover the Philippines",
    learningObjectives: ["Identify the Philippine flag and its parts"],
    essentialQuestion: "What do the symbols on our flag mean?",
    factualBackground: "The Philippine flag has a sun with 8 rays.",
    vocabulary: [{ word: "Watawat", translation: "Flag", language: "Tagalog", hiligaynon: "Hayahay" }],
    subjectConnections: { culture: "Symbols" },
    materials: ["Philippine flag drawing"],
    factualMediaRequirements: ["philippines-flag"],
    mediaReferences: ["philippines-flag"],
    factualSources: [{ source: "NHCP", note: "Verified flag features" }],
    activities: {
      beginnerSupport: "Color the flag.",
      coreActivity: "Count the 8 rays of the sun.",
      advancedChallenge: "Draw what the 3 stars represent."
    },
    interactiveGame: "Flag Match",
    handsOnActivity: "Make a flag",
    knowledgeCheck: [
      { question: "How many rays does the sun on the flag have?", options: ["8", "3"], correctAnswer: "8" }
    ],
    learnerReflection: "I know the Philippine flag.",
    familyChallenge: "Draw the flag together.",
    progressBadge: "Flag Bearer",
    sourceNotes: "NHCP, verified Tagalog/Hiligaynon from KWF",
    mediaAttributionNotes: "Flag image verified",
    accessibilityNotes: "Tactile flag",
    privacyClassification: "family-safe",
    publicationStatus: "pilot",
    teacherPreparation: "Prepare flag materials.",
    teacherAnswerKey: { "Q1": "8" }
  },
  {
    id: "lesson-8-mountains",
    date: "2026-08-18",
    weekday: "Tuesday",
    title: "Mountains and Volcanoes",
    topic: "Philippine mountains",
    ageRange: "6-8",
    unit: "Discover the Philippines",
    learningObjectives: ["Learn about mountains and volcanoes in the Philippines"],
    essentialQuestion: "What makes Mayon Volcano special?",
    factualBackground: "Mayon Volcano is famous for its near-symmetrical cone shape.",
    vocabulary: [
      { word: "Bundok", translation: "Mountain", language: "Tagalog", hiligaynon: "Bukid" },
      { word: "Bulkan", translation: "Volcano", language: "Tagalog", hiligaynon: "Bulkan" }
    ],
    subjectConnections: { science: "Volcanoes" },
    materials: ["Photos of Mayon Volcano"],
    factualMediaRequirements: ["philippines-regions-photo"],
    mediaReferences: ["philippines-regions-photo"],
    factualSources: [{ source: "PHIVOLCS", note: "Verified Mayon near-symmetrical shape" }],
    activities: {
      beginnerSupport: "Point to the volcano.",
      coreActivity: "Describe the near-symmetrical cone shape of Mayon.",
      advancedChallenge: "Explain what a volcano is."
    },
    interactiveGame: "Mountain Match",
    handsOnActivity: "Make a clay volcano",
    knowledgeCheck: [
      { question: "What shape is Mayon Volcano?", options: ["Near-symmetrical cone", "Square"], correctAnswer: "Near-symmetrical cone" }
    ],
    learnerReflection: "I learned about volcanoes.",
    familyChallenge: "Make a volcano experiment at home.",
    progressBadge: "Volcano Explorer",
    sourceNotes: "PHIVOLCS, verified Tagalog/Hiligaynon from KWF",
    mediaAttributionNotes: "Photo verified",
    accessibilityNotes: "Clear visuals",
    privacyClassification: "family-safe",
    publicationStatus: "pilot",
    teacherPreparation: "Prepare clay.",
    teacherAnswerKey: { "Q1": "Near-symmetrical cone" }
  },
  {
    id: "lesson-9-rivers-beaches",
    date: "2026-08-21",
    weekday: "Friday",
    title: "Rivers and Beaches",
    topic: "Philippine rivers and beaches",
    ageRange: "6-8",
    unit: "Discover the Philippines",
    learningObjectives: ["Explore natural water forms and terraces"],
    essentialQuestion: "Who carved the Banaue Rice Terraces?",
    factualBackground: "The Banaue Rice Terraces were carved by ancestors.",
    vocabulary: [
      { word: "Ilog", translation: "River", language: "Tagalog", hiligaynon: "Suba" },
      { word: "Dagat", translation: "Sea", language: "Tagalog", hiligaynon: "Dagat" }
    ],
    subjectConnections: { geography: "Waterforms" },
    materials: ["Photos of rivers and terraces"],
    factualMediaRequirements: ["banaue-terraces-photo"],
    mediaReferences: ["banaue-terraces-photo"],
    factualSources: [{ source: "UNESCO", note: "Verified Banaue Rice Terraces history" }],
    activities: {
      beginnerSupport: "Point to the water.",
      coreActivity: "Learn about how the terraces were carved.",
      advancedChallenge: "Draw a river flowing down a mountain."
    },
    interactiveGame: "Water Match",
    handsOnActivity: "Paint a terrace",
    knowledgeCheck: [
      { question: "Who carved the Banaue Rice Terraces?", options: ["Ancestors", "Aliens"], correctAnswer: "Ancestors" }
    ],
    learnerReflection: "I love nature.",
    familyChallenge: "Visit a river or beach.",
    progressBadge: "Water Explorer",
    sourceNotes: "UNESCO, verified Tagalog/Hiligaynon from KWF",
    mediaAttributionNotes: "Photo verified",
    accessibilityNotes: "Clear visuals",
    privacyClassification: "family-safe",
    publicationStatus: "pilot",
    teacherPreparation: "Prepare paints.",
    teacherAnswerKey: { "Q1": "Ancestors" }
  },
  {
    id: "lesson-10-animals",
    date: "2026-08-24",
    weekday: "Monday",
    title: "Animals of the Philippines",
    topic: "Philippine animals",
    ageRange: "6-8",
    unit: "Discover the Philippines",
    learningObjectives: ["Identify the Philippine Eagle"],
    essentialQuestion: "What is the largest eagle in the Philippines?",
    factualBackground: "The Philippine Eagle is one of the largest eagles.",
    vocabulary: [{ word: "Agila", translation: "Eagle", language: "Tagalog", hiligaynon: "Agila" }],
    subjectConnections: { science: "Animals" },
    materials: ["Photo of Philippine Eagle"],
    factualMediaRequirements: ["philippine-eagle-photo"],
    mediaReferences: ["philippine-eagle-photo"],
    factualSources: [{ source: "PEF", note: "Verified Philippine Eagle facts" }],
    activities: {
      beginnerSupport: "Make an eagle sound.",
      coreActivity: "Learn why the Philippine Eagle is special.",
      advancedChallenge: "Draw an eagle with large wings."
    },
    interactiveGame: "Animal Match",
    handsOnActivity: "Eagle mask making",
    knowledgeCheck: [
      { question: "Is the Philippine Eagle large or small?", options: ["Large", "Small"], correctAnswer: "Large" }
    ],
    learnerReflection: "I learned about the eagle.",
    familyChallenge: "Act like an eagle at home.",
    progressBadge: "Animal Explorer",
    sourceNotes: "PEF, verified Tagalog/Hiligaynon from KWF",
    mediaAttributionNotes: "Photo verified",
    accessibilityNotes: "Clear audio",
    privacyClassification: "family-safe",
    publicationStatus: "pilot",
    teacherPreparation: "Prepare mask templates.",
    teacherAnswerKey: { "Q1": "Large" }
  },
  {
    id: "lesson-11-plants",
    date: "2026-08-25",
    weekday: "Tuesday",
    title: "Plants and Fruits",
    topic: "Philippine plants",
    ageRange: "6-8",
    unit: "Discover the Philippines",
    learningObjectives: ["Identify the national fruit"],
    essentialQuestion: "What is the national fruit of the Philippines?",
    factualBackground: "The mango is the national fruit.",
    vocabulary: [{ word: "Mangga", translation: "Mango", language: "Tagalog", hiligaynon: "Paho" }],
    subjectConnections: { science: "Plants" },
    materials: ["Picture of a mango"],
    factualMediaRequirements: ["mango-photo"],
    mediaReferences: ["mango-photo"],
    factualSources: [{ source: "DA", note: "Verified national fruit" }],
    activities: {
      beginnerSupport: "Color the mango.",
      coreActivity: "Learn about the mango tree.",
      advancedChallenge: "List 3 other fruits."
    },
    interactiveGame: "Fruit Match",
    handsOnActivity: "Draw a fruit basket",
    knowledgeCheck: [
      { question: "What is the national fruit?", options: ["Mango", "Apple"], correctAnswer: "Mango" }
    ],
    learnerReflection: "I like mangoes.",
    familyChallenge: "Eat a fruit together.",
    progressBadge: "Plant Explorer",
    sourceNotes: "DA, verified Tagalog/Hiligaynon from KWF",
    mediaAttributionNotes: "Photo verified",
    accessibilityNotes: "High contrast",
    privacyClassification: "family-safe",
    publicationStatus: "pilot",
    teacherPreparation: "Prepare fruit pictures.",
    teacherAnswerKey: { "Q1": "Mango" }
  },
  {
    id: "lesson-12-language",
    date: "2026-08-28",
    weekday: "Friday",
    title: "The Filipino Language",
    topic: "Philippine language",
    ageRange: "6-8",
    unit: "Discover the Philippines",
    learningObjectives: ["Learn a common greeting"],
    essentialQuestion: "How do we welcome people in the Philippines?",
    factualBackground: "Mabuhay is a common greeting.",
    vocabulary: [{ word: "Mabuhay", translation: "Welcome/Long live", language: "Tagalog", hiligaynon: "Mabuhay" }],
    subjectConnections: { language: "Greetings" },
    materials: ["Welcome sign"],
    factualMediaRequirements: [],
    factualSources: [{ source: "KWF", note: "Verified Mabuhay usage" }],
    activities: {
      beginnerSupport: "Say Mabuhay.",
      coreActivity: "Practice saying Mabuhay with a smile.",
      advancedChallenge: "Make a welcome sign."
    },
    interactiveGame: "Greeting Game",
    handsOnActivity: "Decorate a Mabuhay sign",
    knowledgeCheck: [
      { question: "What does Mabuhay mean?", options: ["Welcome", "Goodbye"], correctAnswer: "Welcome" }
    ],
    learnerReflection: "I know how to say welcome.",
    familyChallenge: "Say Mabuhay to guests.",
    progressBadge: "Language Explorer",
    sourceNotes: "KWF, verified Tagalog/Hiligaynon from KWF",
    mediaAttributionNotes: "None",
    accessibilityNotes: "Clear audio",
    privacyClassification: "family-safe",
    publicationStatus: "pilot",
    teacherPreparation: "Prepare signs.",
    teacherAnswerKey: { "Q1": "Welcome" }
  },
  {
    id: "lesson-13-august-review",
    date: "2026-08-31",
    weekday: "Monday",
    title: "August Review and Showcase",
    topic: "August review",
    ageRange: "6-8",
    unit: "Discover the Philippines",
    learningObjectives: ["Review regions and symbols"],
    essentialQuestion: "What did we learn this month?",
    factualBackground: "Review of regions and symbols.",
    vocabulary: [],
    subjectConnections: { geography: "Review" },
    materials: ["Review flashcards"],
    factualMediaRequirements: [],
    factualSources: [{ source: "Maps", note: "Verified review material" }],
    activities: {
      beginnerSupport: "Review one word.",
      coreActivity: "Participate in the review game.",
      advancedChallenge: "Teach the class something you learned."
    },
    interactiveGame: "August Review Quiz",
    handsOnActivity: "Showcase portfolio",
    knowledgeCheck: [
      { question: "What is a group of islands called?", options: ["Archipelago", "Forest"], correctAnswer: "Archipelago" }
    ],
    learnerReflection: "I learned a lot in August.",
    familyChallenge: "Show your family your work.",
    progressBadge: "August Scholar",
    sourceNotes: "Maps, verified",
    mediaAttributionNotes: "None",
    accessibilityNotes: "Clear visuals",
    privacyClassification: "family-safe",
    publicationStatus: "pilot",
    teacherPreparation: "Prepare portfolio materials.",
    teacherAnswerKey: { "Q1": "Archipelago" }
  }
];
