// ─────────────────────────────────────────────────────────────
// COOKING & BAKING STUDIO — every recipe follows the same shape,
// so adding one here automatically creates its full recipe page.
// ─────────────────────────────────────────────────────────────

export type Recipe = {
  id: string;
  name: string;
  filipinoName: string;
  emoji: string;
  type: "Cooking" | "Baking" | "No-Bake";
  difficulty: "Easy" | "Medium";
  time: string;
  photoNote: string; // description for the real-photo placeholder
  ingredients: string[];
  tools: string[];
  steps: string[];
  safety: string[];
  tagalogWords: { word: string; meaning: string }[];
  hiligaynonWords: { word: string; meaning: string }[];
  culturalNote: string;
  discussionQuestion: string;
};

export const recipes: Recipe[] = [
  {
    id: "mango-float",
    name: "Mango Float",
    filipinoName: "Crema de Mangga",
    emoji: "🥭",
    type: "No-Bake",
    difficulty: "Easy",
    time: "20 min + chill overnight",
    photoNote: "Golden mango slices on creamy white layers in a glass dish",
    ingredients: [
      "3–4 ripe mangoes, sliced thin",
      "2 packs graham crackers",
      "2 cups all-purpose cream (or heavy whipping cream), chilled",
      "1 can (14 oz) sweetened condensed milk",
    ],
    tools: ["8x8 glass dish", "Mixing bowl", "Whisk or hand mixer", "Spatula", "Knife & cutting board (adult job)"],
    steps: [
      "Chill the cream in the fridge for at least 2 hours (overnight is best).",
      "ADULT JOB: Peel and slice the mangoes into thin strips. Kids can arrange them on a plate.",
      "Whip the chilled cream in a big bowl until it thickens and forms soft peaks.",
      "Slowly pour in the condensed milk while folding gently with a spatula. Taste test allowed!",
      "Lay a layer of graham crackers on the bottom of the dish.",
      "Spread a layer of the cream mixture over the crackers.",
      "Arrange a layer of mango slices on top of the cream.",
      "Repeat the layers: crackers, cream, mangoes — usually 3 layers fit!",
      "Finish with cream and your prettiest mango slices on top.",
      "Cover and chill in the freezer for at least 4 hours, or overnight in the fridge.",
      "Slice, serve, and say 'Masarap!' (Delicious!)",
    ],
    safety: [
      "Knives are an adult job — kids can layer, whip, and arrange.",
      "Wash hands before starting and after touching fruit.",
      "Wipe up spills right away so no one slips.",
    ],
    tagalogWords: [
      { word: "Mangga", meaning: "Mango" },
      { word: "Masarap", meaning: "Delicious" },
      { word: "Matamis", meaning: "Sweet" },
      { word: "Gatas", meaning: "Milk" },
    ],
    hiligaynonWords: [
      { word: "Pahò", meaning: "Mango" },
      { word: "Namit", meaning: "Delicious" },
      { word: "Matam-is", meaning: "Sweet" },
      { word: "Gatas", meaning: "Milk" },
    ],
    culturalNote:
      "Mango float is the star of Filipino family gatherings. The island of Guimaras, near Teacher Sharon's home region, is famous for the sweetest mangoes in the world — they even hold mango-eating festivals every May!",
    discussionQuestion: "Why do you think Filipino families love making desserts together for special days? What is our family's 'special day' food?",
  },
  {
    id: "turon",
    name: "Turon",
    filipinoName: "Banana Spring Rolls",
    emoji: "🍌",
    type: "Cooking",
    difficulty: "Medium",
    time: "30 min",
    photoNote: "Golden crispy banana rolls with caramelized sugar shine",
    ingredients: [
      "6 saba bananas (or regular bananas), sliced lengthwise",
      "12 lumpia/spring roll wrappers",
      "1 cup brown sugar",
      "Ripe jackfruit strips (optional)",
      "Cooking oil for frying",
    ],
    tools: ["Frying pan", "Tongs", "Plate with paper towels", "Small bowl of water for sealing wrappers"],
    steps: [
      "Roll each banana slice in brown sugar until coated.",
      "Place a banana slice (and jackfruit strip if using) on a wrapper.",
      "Fold the sides in and roll it up tight like a little sleeping bag. Seal the edge with a dab of water.",
      "ADULT JOB: Heat oil in the pan over medium heat.",
      "ADULT JOB: Fry the rolls until golden and crispy, sprinkling a little brown sugar into the oil to caramelize.",
      "Drain on paper towels, let them cool a few minutes — the inside is HOT!",
    ],
    safety: [
      "Hot oil is strictly an adult job — kids roll, adults fry.",
      "Stand back from the pan while frying.",
      "Let turon cool before the first bite — melted sugar stays hot!",
    ],
    tagalogWords: [
      { word: "Saging", meaning: "Banana" },
      { word: "Mainit", meaning: "Hot" },
    ],
    hiligaynonWords: [
      { word: "Saging", meaning: "Banana" },
      { word: "Mainit", meaning: "Hot" },
    ],
    culturalNote: "Turon is the classic Filipino merienda (afternoon snack), sold from street carts with a wonderful caramel smell that fills the whole neighborhood.",
    discussionQuestion: "In the Philippines, merienda is a special snack time to rest and chat. What would our family's perfect merienda look like?",
  },
  {
    id: "graham-cake",
    name: "Graham Cake",
    filipinoName: "Crema de Fruta Graham",
    emoji: "🍰",
    type: "No-Bake",
    difficulty: "Easy",
    time: "20 min + chill",
    photoNote: "Layered no-bake cake topped with colorful fruit cocktail",
    ingredients: [
      "2 packs graham crackers",
      "2 cups all-purpose cream, chilled",
      "1 can condensed milk",
      "1 large can fruit cocktail, drained well",
    ],
    tools: ["8x8 dish", "Mixing bowl", "Whisk", "Spatula", "Can opener (adult job)"],
    steps: [
      "Whip the chilled cream until soft and fluffy.",
      "Fold in the condensed milk gently.",
      "Stir in most of the drained fruit cocktail (save some pretty pieces for the top).",
      "Layer: graham crackers, then cream-fruit mixture. Repeat!",
      "Decorate the top with the saved fruit pieces.",
      "Chill overnight — patience makes it perfect!",
    ],
    safety: ["Can openers and can edges are sharp — adult job.", "Wash hands before layering."],
    tagalogWords: [
      { word: "Prutas", meaning: "Fruit" },
      { word: "Keyk", meaning: "Cake" },
    ],
    hiligaynonWords: [
      { word: "Prutas", meaning: "Fruit" },
      { word: "Keyk", meaning: "Cake" },
    ],
    culturalNote: "Graham cake shows Filipino creativity — a fancy celebration cake with no oven needed, perfect for the tropical heat!",
    discussionQuestion: "Filipinos turn simple ingredients into celebration food. What simple things does our family turn into something special?",
  },
  {
    id: "fruit-salad",
    name: "Filipino Fruit Salad",
    filipinoName: "Ensaladang Prutas",
    emoji: "🍑",
    type: "No-Bake",
    difficulty: "Easy",
    time: "15 min + chill",
    photoNote: "Creamy fruit salad with cherries in a festive glass bowl",
    ingredients: [
      "1 large can fruit cocktail, drained overnight",
      "1 cup all-purpose cream",
      "1/2 can condensed milk",
      "1 cup shredded young coconut or coconut strips (optional)",
      "Cheese cubes (optional — a Filipino twist!)",
    ],
    tools: ["Big mixing bowl", "Strainer", "Spatula"],
    steps: [
      "Drain the fruit cocktail really well (overnight in a strainer is the secret).",
      "Mix cream and condensed milk in a big bowl.",
      "Fold in the fruit, coconut, and cheese cubes if using.",
      "Chill for at least 4 hours. Serve cold with a big spoon and a bigger smile!",
    ],
    safety: ["Wash hands before mixing.", "Adult helps with cheese cubing."],
    tagalogWords: [
      { word: "Niyog", meaning: "Coconut" },
      { word: "Malamig", meaning: "Cold" },
    ],
    hiligaynonWords: [
      { word: "Lubi", meaning: "Coconut" },
      { word: "Matugnaw", meaning: "Cold" },
    ],
    culturalNote: "No Filipino Christmas or birthday table is complete without fruit salad — and yes, Filipinos really do put cheese in it. Don't knock it till you try it!",
    discussionQuestion: "Every family has a dish that must be at every celebration. What is ours?",
  },
  {
    id: "filipino-pancakes",
    name: "Pancakes with Filipino Words",
    filipinoName: "Panqueque",
    emoji: "🥞",
    type: "Cooking",
    difficulty: "Easy",
    time: "25 min",
    photoNote: "A tall stack of fluffy pancakes with mango slices and honey",
    ingredients: [
      "1 1/2 cups flour (harina)",
      "2 tbsp sugar (asukal)",
      "1 tbsp baking powder",
      "1 egg (itlog)",
      "1 1/4 cups milk (gatas)",
      "2 tbsp melted butter (mantikilya)",
      "Sliced mango or banana for topping",
    ],
    tools: ["Mixing bowls", "Whisk", "Griddle or pan", "Spatula", "Measuring cups"],
    steps: [
      "Whisk the dry ingredients: harina (flour), asukal (sugar), baking powder.",
      "In another bowl whisk the itlog (egg), gatas (milk), and mantikilya (butter).",
      "Pour wet into dry and stir just until combined — lumps are okay!",
      "ADULT JOB: Heat the pan over medium heat.",
      "Pour small circles of batter. Flip when bubbles pop on top.",
      "Stack, top with mangga (mango) or saging (banana), and say 'Kain tayo!' — Let's eat!",
    ],
    safety: ["The pan and flipping are adult jobs.", "Kids measure, whisk, and decorate."],
    tagalogWords: [
      { word: "Harina", meaning: "Flour" },
      { word: "Asukal", meaning: "Sugar" },
      { word: "Itlog", meaning: "Egg" },
      { word: "Gatas", meaning: "Milk" },
      { word: "Almusal", meaning: "Breakfast" },
    ],
    hiligaynonWords: [
      { word: "Harina", meaning: "Flour" },
      { word: "Kalamay", meaning: "Sugar" },
      { word: "Itlog", meaning: "Egg" },
      { word: "Pamahaw", meaning: "Breakfast" },
    ],
    culturalNote: "This is a language lesson disguised as breakfast! Filipino kitchens mix Spanish, Malay, and English words — just like this recipe mixes cultures.",
    discussionQuestion: "How many Filipino words can you remember while eating your pancakes? Quiz each other!",
  },
  {
    id: "lumpia",
    name: "Lumpia",
    filipinoName: "Lumpiang Shanghai",
    emoji: "🌯",
    type: "Cooking",
    difficulty: "Medium",
    time: "45 min",
    photoNote: "Crispy golden lumpia rolls with sweet chili dipping sauce",
    ingredients: [
      "1 lb ground pork or chicken",
      "1 carrot, finely grated",
      "1 small onion, minced",
      "2 cloves garlic, minced",
      "1 egg",
      "Salt and pepper",
      "1 pack lumpia wrappers",
      "Oil for frying",
      "Sweet chili sauce for dipping",
    ],
    tools: ["Mixing bowl", "Frying pan", "Tongs", "Small bowl of water"],
    steps: [
      "Mix the meat, carrot, onion, garlic, egg, salt, and pepper in a bowl. Hands work best (wash them first)!",
      "Place a spoonful of filling on a wrapper and roll it thin and tight, like a little log.",
      "Seal the edge with water. Roll the whole batch as a family assembly line!",
      "ADULT JOB: Fry in hot oil until deep golden brown and cooked through.",
      "Drain, cool slightly, and dip away!",
    ],
    safety: [
      "Raw meat: wash hands and surfaces well after touching.",
      "Frying is strictly an adult job.",
      "Make sure lumpia is fully cooked inside before eating.",
    ],
    tagalogWords: [
      { word: "Lumpia", meaning: "Spring roll" },
      { word: "Handaan", meaning: "Feast / party" },
    ],
    hiligaynonWords: [
      { word: "Lumpia", meaning: "Spring roll" },
      { word: "Punsyon", meaning: "Feast / party" },
    ],
    culturalNote: "Lumpia is the first dish to disappear at every Filipino party. Rolling lumpia together around the table is a beloved family tradition — many hands make light (and delicious) work. That's bayanihan in the kitchen!",
    discussionQuestion: "Rolling lumpia goes faster when everyone helps. What other jobs at home become fun when we do them together?",
  },
  {
    id: "pancit",
    name: "Pancit",
    filipinoName: "Pancit Bihon",
    emoji: "🍜",
    type: "Cooking",
    difficulty: "Medium",
    time: "40 min",
    photoNote: "Colorful stir-fried noodles with vegetables and calamansi wedges",
    ingredients: [
      "8 oz rice noodles (bihon), soaked in water",
      "2 cups chicken, cooked and shredded",
      "2 cups mixed vegetables (cabbage, carrots, green beans), sliced thin",
      "3 cloves garlic, minced",
      "1 onion, sliced",
      "1/4 cup soy sauce",
      "2 cups chicken broth",
      "Calamansi or lemon wedges",
    ],
    tools: ["Large pan or wok", "Tongs", "Cutting board & knife (adult job)"],
    steps: [
      "Soak the noodles in water until soft, then drain.",
      "ADULT JOB: Sauté garlic and onion until fragrant.",
      "Add chicken and vegetables; stir-fry until the veggies are bright and crisp.",
      "Pour in soy sauce and broth; bring to a gentle simmer.",
      "Add noodles and toss until they drink up all the sauce.",
      "Serve with calamansi squeezed on top — and remember to wish for LONG LIFE!",
    ],
    safety: ["Hot wok and knife work are adult jobs.", "Kids can soak noodles, tear cabbage, and squeeze calamansi."],
    tagalogWords: [
      { word: "Pancit", meaning: "Noodles" },
      { word: "Gulay", meaning: "Vegetables" },
      { word: "Mahabang buhay", meaning: "Long life" },
    ],
    hiligaynonWords: [
      { word: "Pancit", meaning: "Noodles" },
      { word: "Utan", meaning: "Vegetables" },
      { word: "Malawig nga kabuhi", meaning: "Long life" },
    ],
    culturalNote: "Pancit is served at every Filipino birthday because the long noodles stand for a long, blessed life. Never cut the noodles — slurp them!",
    discussionQuestion: "Pancit means wishing someone a long life. What blessing would you wish over each person in our family?",
  },
  {
    id: "chicken-adobo",
    name: "Chicken Adobo",
    filipinoName: "Adobong Manok",
    emoji: "🍗",
    type: "Cooking",
    difficulty: "Medium",
    time: "1 hour",
    photoNote: "Glossy chicken adobo over steaming white rice",
    ingredients: [
      "2 lbs chicken thighs or drumsticks",
      "1/2 cup soy sauce",
      "1/3 cup white vinegar",
      "6 cloves garlic, crushed",
      "3 bay leaves",
      "1 tsp whole peppercorns",
      "1 tbsp brown sugar (optional)",
      "Cooked rice to serve",
    ],
    tools: ["Large pot with lid", "Tongs", "Measuring cups"],
    steps: [
      "Kids: measure the soy sauce, vinegar, and count the garlic, bay leaves, and peppercorns.",
      "Marinate the chicken in soy sauce and garlic for 30 minutes (or overnight).",
      "ADULT JOB: Brown the chicken in a pot.",
      "Add the marinade, vinegar, bay leaves, and peppercorns. DO NOT STIR yet — that's the adobo rule (it lets the vinegar mellow)!",
      "Simmer covered for 30–40 minutes until tender.",
      "Add sugar if you like it sweeter; simmer until the sauce is glossy.",
      "Serve over rice. This is the taste of the Philippines!",
    ],
    safety: ["Raw chicken: wash hands well; adult handles all meat.", "Simmering pot stays adult-side."],
    tagalogWords: [
      { word: "Manok", meaning: "Chicken" },
      { word: "Kanin", meaning: "Rice (cooked)" },
      { word: "Bawang", meaning: "Garlic" },
      { word: "Suka", meaning: "Vinegar" },
    ],
    hiligaynonWords: [
      { word: "Manok", meaning: "Chicken" },
      { word: "Kan-on", meaning: "Rice (cooked)" },
      { word: "Ahos", meaning: "Garlic" },
      { word: "Langgaw", meaning: "Vinegar" },
    ],
    culturalNote: "Adobo is the unofficial national dish of the Philippines. Every family has its own secret version passed down through generations — sweeter, saltier, with coconut milk, with potatoes. Yours starts today!",
    discussionQuestion: "Adobo recipes are passed from grandparents to parents to kids. What recipe or tradition do you want to pass on someday?",
  },
  {
    id: "halo-halo",
    name: "Halo-Halo",
    filipinoName: "Haluhalo",
    emoji: "🍧",
    type: "No-Bake",
    difficulty: "Easy",
    time: "20 min",
    photoNote: "A tall glass rainbow of shaved ice, fruits, jellies, and purple ube ice cream",
    ingredients: [
      "Shaved or crushed ice",
      "Sweetened banana slices",
      "Sweetened beans or chickpeas (traditional!) or jellies",
      "Fruit cocktail or fresh fruit",
      "Coconut strips",
      "Evaporated milk",
      "A scoop of ice cream (ube if you can find it!)",
      "Leche flan or pudding cubes (optional)",
    ],
    tools: ["Tall glasses", "Long spoons", "Blender or ice crusher (adult job)"],
    steps: [
      "Layer the sweet ingredients in the bottom of each tall glass — everyone designs their own!",
      "ADULT JOB: Crush the ice in the blender.",
      "Pile the ice high like a snowy mountain.",
      "Pour evaporated milk over the ice.",
      "Crown it with ice cream and extra toppings.",
      "Now the most important step: MIX! 'Halo-halo' means 'mix-mix' — stir everything together and enjoy!",
    ],
    safety: ["Blender is an adult job.", "Brain freeze warning: small bites!"],
    tagalogWords: [
      { word: "Halo-halo", meaning: "Mix-mix" },
      { word: "Yelo", meaning: "Ice" },
      { word: "Ube", meaning: "Purple yam" },
    ],
    hiligaynonWords: [
      { word: "Halo-halo", meaning: "Mix-mix" },
      { word: "Yelo", meaning: "Ice" },
    ],
    culturalNote: "Halo-halo is the Philippines' favorite way to beat the tropical heat. Every region adds its own twist — the fun is that no two glasses are ever the same, just like families!",
    discussionQuestion: "Halo-halo is many different things mixed into one wonderful treat. How is our family like a halo-halo?",
  },
  {
    id: "banana-cue",
    name: "Banana Cue",
    filipinoName: "Bananakyu",
    emoji: "🍢",
    type: "Cooking",
    difficulty: "Easy",
    time: "20 min",
    photoNote: "Caramel-glazed bananas on bamboo skewers",
    ingredients: [
      "6 saba bananas (or firm regular bananas)",
      "1 cup brown sugar",
      "Cooking oil",
      "Bamboo skewers",
    ],
    tools: ["Frying pan", "Tongs", "Skewers", "Paper towels"],
    steps: [
      "ADULT JOB: Heat oil in a pan over medium heat.",
      "ADULT JOB: Fry the bananas for a few minutes until they start to soften.",
      "ADULT JOB: Sprinkle brown sugar into the oil — it will melt and coat the bananas in caramel.",
      "ADULT JOB: Remove and let cool until safe to touch.",
      "Kids: thread the cooled bananas onto skewers like a street vendor!",
      "Eat them the Filipino way — straight off the stick with a big smile.",
    ],
    safety: [
      "Caramelized sugar is EXTREMELY hot — all frying is adult-only.",
      "Wait for bananas to cool before skewering and eating.",
      "Skewer points are sharp — walk, don't run!",
    ],
    tagalogWords: [
      { word: "Saging", meaning: "Banana" },
      { word: "Matamis", meaning: "Sweet" },
    ],
    hiligaynonWords: [
      { word: "Saging", meaning: "Banana" },
      { word: "Matam-is", meaning: "Sweet" },
    ],
    culturalNote: "Banana cue is the sound of Filipino afternoons — vendors' carts, kids coming home from school, and the sweet smell of caramel on every street corner.",
    discussionQuestion: "Street food brings neighbors together in the Philippines. What food brings our neighborhood or church family together?",
  },
  {
    id: "puto",
    name: "Puto",
    filipinoName: "Puto",
    emoji: "🧁",
    type: "Baking",
    difficulty: "Easy",
    time: "35 min",
    photoNote: "Fluffy white steamed mini cakes, some topped with cheese",
    ingredients: [
      "2 cups flour",
      "1 cup sugar",
      "1 tbsp baking powder",
      "1 1/2 cups milk or water",
      "1 egg white (optional, for fluffiness)",
      "Cheese slices or salted egg for topping",
      "Food coloring (optional, for rainbow puto!)",
    ],
    tools: ["Steamer (or a pot with a rack)", "Small molds or silicone muffin cups", "Mixing bowl", "Whisk"],
    steps: [
      "Whisk flour, sugar, and baking powder together.",
      "Add milk and whisk into a smooth pancake-like batter.",
      "Selah's favorite part: divide and tint with food coloring for rainbow puto!",
      "Fill the little molds 3/4 full.",
      "Top each with a small piece of cheese.",
      "ADULT JOB: Steam for 10–15 minutes until a toothpick comes out clean.",
      "Cool slightly, pop out of the molds, and admire your fluffy little clouds!",
    ],
    safety: ["Steam burns are sneaky — the steamer is an adult job.", "Let puto cool before unmolding."],
    tagalogWords: [
      { word: "Puto", meaning: "Steamed rice cake" },
      { word: "Keso", meaning: "Cheese" },
      { word: "Malambot", meaning: "Soft" },
    ],
    hiligaynonWords: [
      { word: "Puto", meaning: "Steamed rice cake" },
      { word: "Keso", meaning: "Cheese" },
      { word: "Mahumok", meaning: "Soft" },
    ],
    culturalNote: "Puto is often paired with savory dishes like dinuguan, but kids love it plain with cheese. It's baking without an oven — steaming is an old and clever Filipino technique!",
    discussionQuestion: "Puto is soft, simple, and shared at every gathering. Why do you think simple foods often become the most loved?",
  },
  {
    id: "bibingka",
    name: "Bibingka",
    filipinoName: "Bibingka",
    emoji: "🥥",
    type: "Baking",
    difficulty: "Medium",
    time: "45 min",
    photoNote: "Golden rice cake in a banana leaf with butter, cheese, and coconut on top",
    ingredients: [
      "2 cups rice flour",
      "3/4 cup sugar",
      "1 tbsp baking powder",
      "3 eggs",
      "1 can (13.5 oz) coconut milk",
      "1/4 cup melted butter",
      "Banana leaves (or parchment paper)",
      "Toppings: cheese, grated coconut, extra butter and sugar",
    ],
    tools: ["Round baking pan", "Mixing bowls", "Whisk", "Oven (adult job)"],
    steps: [
      "ADULT JOB: Preheat the oven to 375°F (190°C).",
      "Line the pan with banana leaves (or parchment) — this gives bibingka its famous aroma!",
      "Whisk rice flour, sugar, and baking powder.",
      "In another bowl, whisk eggs, coconut milk, and melted butter.",
      "Combine wet and dry into a smooth batter and pour into the pan.",
      "ADULT JOB: Bake 25–30 minutes until golden and set.",
      "Brush with butter, sprinkle sugar, cheese, and grated coconut on top.",
      "Serve warm — bibingka is a warm hug in food form!",
    ],
    safety: ["Oven work is adult-only.", "The pan stays hot long after baking — use mitts and patience."],
    tagalogWords: [
      { word: "Bibingka", meaning: "Rice cake" },
      { word: "Niyog", meaning: "Coconut" },
      { word: "Mainit-init", meaning: "Nice and warm" },
    ],
    hiligaynonWords: [
      { word: "Bibingka", meaning: "Rice cake" },
      { word: "Lubi", meaning: "Coconut" },
    ],
    culturalNote: "Bibingka is traditionally sold warm outside churches in the early morning during December. Families eat it together as the sun rises — food, faith, and family all in one warm bite.",
    discussionQuestion: "Bibingka is eaten after early morning gatherings. What morning traditions could our family start together?",
  },
];

export function getRecipe(id: string): Recipe | undefined {
  return recipes.find((r) => r.id === id);
}
